#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable
#include "sppm_commons.h"
#include "../../utils.glsl"
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
#include "../../bda.glsl"
SCENE_BUFFER_SCALAR(atomic_data, AtomicData);
void main() {
    const float max_radius = DEREF(atomic_data).max_radius;
    vec3 data = DEREF(atomic_data).max_bnds - DEREF(atomic_data).min_bnds;
    float max_comp = max(data.x, max(data.y, data.z));
    int base_grid_res = int(max_comp / max_radius);
    if (max_comp > 0. && max_radius > 0.) {
        DEREF(atomic_data).grid_res =
            max(ivec3(base_grid_res * data / max_comp), ivec3(1));
    } else {
        DEREF(atomic_data).grid_res = ivec3(0, 0, 0);
    }
}