#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable

#include "../../utils.glsl"
#include "sppm_commons.h"

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(binding = 1) uniform sampler2D scene_textures[];
layout(push_constant) uniform _PushConstantRay { PCSPPM pc; };
#include "../../scene_buffers.glsl"
SCENE_BUFFER(sppm_data, SPPMData);
SCENE_BUFFER_SCALAR(atomic_data, AtomicData);
SCENE_BUFFER(photon, PhotonHash);

#include "../../surface.glsl"

uint size = pc.width * pc.height;

uint screen_size = pc.width * pc.height;

#include "../../bsdf_commons.glsl"

vec3 normalize_grid(vec3 p, vec3 min_bnds, vec3 max_bnds) {
    return (p - min_bnds) / (max_bnds - min_bnds);
}

ivec3 get_grid_idx(vec3 p, vec3 min_bnds, vec3 max_bnds, ivec3 grid_res) {
    ivec3 res = ivec3(normalize_grid(p, min_bnds, max_bnds) * grid_res);
    clamp(res, vec3(0), grid_res - vec3(1));
    return res;
}

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= size) {
        return;
    }
    const SurfaceRef surface_ref = DEREF(sppm_data)[idx].surface;
    if (!surface_ref_valid(surface_ref)) {
        return;
    }
    const SurfaceData surface = load_surface(surface_ref);
    const Material mat = load_material(surface.material_idx, surface.uv);
    const vec3 wo = DEREF(sppm_data)[idx].wo;
    vec3 n_s = surface.n_s;
    vec3 n_g = surface.n_g;
    const bool side = face_forward(n_s, n_g, wo);
    const vec3 p = DEREF(sppm_data)[idx].p;
    float r = DEREF(sppm_data)[idx].radius;
    if (r < EPS) {
        r = EPS;
    }
    const float r_sqr = r * r;
    ivec3 grid_min_bnds_idx =
        get_grid_idx(p - r, DEREF(atomic_data).min_bnds, DEREF(atomic_data).max_bnds,
                     DEREF(atomic_data).grid_res);
    ivec3 grid_max_bnds_idx =
        get_grid_idx(p + r, DEREF(atomic_data).min_bnds, DEREF(atomic_data).max_bnds,
                     DEREF(atomic_data).grid_res);
    for (int x = grid_min_bnds_idx.x; x <= grid_max_bnds_idx.x; x++) {
        for (int y = grid_min_bnds_idx.y; y <= grid_max_bnds_idx.y; y++) {
            for (int z = grid_min_bnds_idx.z; z <= grid_max_bnds_idx.z; z++) {
                uint h = hash(ivec3(x, y, z), screen_size);
                if (DEREF(photon)[h].photon_count > 0) {
                    vec3 pp = p - DEREF(photon)[h].pos;
                    const float dist_sqr = dot(pp, pp);
                    if (dist_sqr > r_sqr) {
                        continue;
                    }
                    if (pc.max_depth < (DEREF(photon)[h].path_len +
                                            DEREF(sppm_data)[idx].path_len + 1)) {
                        continue;
                    }
                    vec3 f = eval_bsdf(n_s, n_g, wo, mat, TRANSPORT_MODE_FROM_CAMERA,
                                       side, DEREF(photon)[h].wi);
                    vec3 phi = DEREF(photon)[h].photon_count *
                               DEREF(photon)[h].throughput * f *
                               DEREF(sppm_data)[idx].throughput;
                    DEREF(sppm_data)[idx].phi += phi;
                    DEREF(sppm_data)[idx].M += 1;
                }
            }
        }
    }
}
