#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable

#include "../../utils.glsl"
#include "sppm_commons.h"
#include "../../bda.glsl"

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout(set = 0, binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(push_constant) uniform _PushConstantRay { PCSPPM pc; };
SCENE_BUFFER(sppm_data, SPPMData);
SCENE_BUFFER_SCALAR(atomic_data, AtomicData);
SCENE_BUFFER(residual, vec4);
uint size = pc.width * pc.height;
shared vec4 data[32];
void main() {
    uint idx = gl_GlobalInvocationID.x;
    vec3 val = vec3(0);
    float radius_val = 0;
    if (idx < size) {
        val = DEREF(sppm_data)[idx].p + DEREF(sppm_data)[idx].radius;
        radius_val = DEREF(sppm_data)[idx].radius;
    }
    val = subgroupMax(val);
    radius_val = subgroupMax(radius_val);
    if (gl_SubgroupInvocationID == 0) {
        data[gl_SubgroupID].xyz = val;
        data[gl_SubgroupID].w = radius_val;
    }
    barrier();
    if (gl_SubgroupID == 0) {
        val = data[gl_SubgroupInvocationID].xyz;
        radius_val = data[gl_SubgroupInvocationID].w;
        subgroupBarrier();
        val = subgroupMax(val);
        radius_val = subgroupMax(radius_val);
    }
    if (gl_LocalInvocationID.x == 0) {
        DEREF(residual)[gl_WorkGroupID.x].xyz = val;
        DEREF(residual)[gl_WorkGroupID.x].w = radius_val;
    }
}