#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable

#include "sppm_commons.h"
#include "../../utils.glsl"

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
#include "../../bda.glsl"
layout(push_constant) uniform _PushConstantRay { PCSPPM pc; };
SCENE_BUFFER_SCALAR(atomic_data, AtomicData);
SCENE_BUFFER(residual, vec4);
SCENE_BUFFER_SCALAR(counter, int);
uint size = pc.width * pc.height;
shared vec3 data[32];
void main() {
    uint idx = gl_GlobalInvocationID.x;
    vec3 val;
    uint limit = DEREF(counter) == 0 ? size : ((size + 1023) >> (10 * DEREF(counter)));
    if (idx >= limit) {
        return;
    }
    val = DEREF(residual)[idx].xyz;
    memoryBarrier();
    barrier();

    val = subgroupMin(val);
    if (gl_SubgroupInvocationID == 0) {
        data[gl_SubgroupID].xyz = val;
    }
    barrier();

    if (gl_SubgroupID == 0) {
        val = data[gl_SubgroupInvocationID].xyz;
        subgroupBarrier();
        val = subgroupMin(val);
    }
    if (gl_LocalInvocationID.x == 0) {
        DEREF(residual)[gl_WorkGroupID.x].xyz = val;
    }
    if (idx == 0) {
        DEREF(counter) += 1;
        DEREF(atomic_data).min_bnds = val;
    }
}