#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

#include "sppm_commons.h"
#include "../../commons.glsl"
#include "../../surface.glsl"
layout(location = 0) rayPayloadEXT SurfaceHitPayload payload;
layout(location = 1) rayPayloadEXT AnyHitPayload any_hit_payload;

layout(push_constant) uniform _PushConstantRay { PCSPPM pc; };
// SPPM buffers
SCENE_BUFFER_SCALAR(atomic_data, AtomicData);
SCENE_BUFFER(photon, PhotonHash);


uint screen_size = gl_LaunchSizeEXT.x * gl_LaunchSizeEXT.y;

const uint flags = gl_RayFlagsOpaqueEXT;
const float tmin = 0.001;
const float tmax = 10000.0;
#define RR_MIN_DEPTH 3
uint pixel_idx = (gl_LaunchIDEXT.x * gl_LaunchSizeEXT.y + gl_LaunchIDEXT.y);
uvec4 seed = init_rng(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy,
                      pc.frame_num ^ pc.random_num);

vec3 normalize_grid(vec3 p, vec3 min_bnds, vec3 max_bnds) {
    return (p - min_bnds) / (max_bnds - min_bnds);
}

ivec3 get_grid_idx(vec3 p, vec3 min_bnds, vec3 max_bnds, ivec3 grid_res) {
    ivec3 res = ivec3(normalize_grid(p, min_bnds, max_bnds) * grid_res);
    clamp(res, vec3(0), grid_res - vec3(1));
    return res;
}

void main() {
    vec4 rands_pos = rand4(seed);
    vec2 rands_dir = rand2(seed);
    const LightLeSample light_sample = sample_light_Le(rands_pos, rands_dir, pc.num_lights);
    if (light_sample.pdf_joint <= 0.0) {
        return;
    }
    vec3 wi = light_sample.wi;
    vec3 pos = light_sample.position;
    vec3 throughput = light_sample.Le * light_sample.cos_from_light / light_sample.pdf_joint;

    for (int d = 0; d < pc.max_depth; d++) {
        traceRayEXT(tlas, flags, 0xFF, 0, 0, 0, pos, tmin, wi, tmax, 0);
        bool found_isect = surface_ref_valid(payload.surface);
        if (!found_isect) {
            break;
        }
        const SurfaceData surface = load_surface(payload.surface);
        const vec3 wo = -wi;
        vec3 n_s = surface.n_s;
        vec3 n_g = surface.n_g;
        const bool side = face_forward(n_s, n_g, wo);
        float cos_wo = dot(wo, n_s);
        Material hit_mat = load_material(surface.material_idx, surface.uv);
        if (d > 0) {
            // Ignore the first bounce
            vec3 min_bnds = DEREF(atomic_data).min_bnds;
            vec3 max_bnds = DEREF(atomic_data).max_bnds;
            ivec3 grid_res = DEREF(atomic_data).grid_res;
            const ivec3 grid_idx =
                get_grid_idx(surface.pos, min_bnds, max_bnds, grid_res);
            const uint h = hash(grid_idx, screen_size);
            DEREF(photon)[h].pos = surface.pos;
            DEREF(photon)[h].wi = -wi;
            DEREF(photon)[h].throughput = throughput;
            DEREF(photon)[h].nrm = n_s;
            DEREF(photon)[h].path_len = d + 1;
            atomicAdd(DEREF(photon)[h].photon_count, 1);
        }
        float pdf_dir, cos_theta;
        const vec3 f = sample_bsdf(n_s, n_g, wo, hit_mat,
                                   TRANSPORT_MODE_FROM_LIGHT, side, wi,
                                   pdf_dir, cos_theta, seed);
        throughput *= f * abs(cos_theta) / pdf_dir;

        if (f == vec3(0) || pdf_dir == 0) {
            break;
        }
        pos = offset_ray(surface.pos, n_g, wi);
        if (d > RR_MIN_DEPTH) {
            float rr_prob = min(0.95f, luminance(throughput));
            if (rr_prob < rand(seed))
                break;
            else
                throughput /= rr_prob;
        }
    }
}
