// https://www.eecs.umich.edu/courses/eecs570/hw/parprefix.pdf
#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable
#include "../../bda.glsl"
#include "pssmlt_commons.h"
#include "../../utils.glsl"

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout(set = 0, binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(push_constant) uniform _PushConstantCompute { PushConstantCompute pc; };

SCENE_BUFFER(residual, float);
SCENE_BUFFER(bootstrap, BootstrapSample);
SCENE_BUFFER_SCALAR(cdf_sum, float);
SCENE_BUFFER(cdf, float);
DESC_BUFFER(pc, block_sum, float);

#define NUM_BANKS 32
#define LOG_NUM_BANKS 5
#define CONFLICT_FREE_OFFSET(index) ((index) >> LOG_NUM_BANKS)
shared float s_data[2048 + 64];
void main() {
    uint tid, ai, bi, mem_ai, mem_bi, bank_offset_a, bank_offset_b;
    // Load data into shared memory
    tid = gl_LocalInvocationID.x;
    mem_ai = (pc.base_idx == 0 ? (gl_WorkGroupID.x * 2 * gl_WorkGroupSize.x)
                               : pc.base_idx) +
             gl_LocalInvocationID.x;
    mem_bi = mem_ai + gl_WorkGroupSize.x;
    ai = tid;
    bi = tid + gl_WorkGroupSize.x;
    bank_offset_a = CONFLICT_FREE_OFFSET(ai);
    bank_offset_b = CONFLICT_FREE_OFFSET(bi);
    const float div = pc.scan_sums == 1 ? 1. : 1. / pc.num_elems;
    const bool valid_a = ai < pc.n;
    const bool valid_b = bi < pc.n;
    s_data[ai + bank_offset_a] =
        valid_a ? (pc.scan_sums == 0 ? DEREF(bootstrap)[mem_ai].lum * div
                                     : DEREF(block_sum)[mem_ai])
                : 0;
    s_data[bi + bank_offset_b] =
        valid_b ? (pc.scan_sums == 0 ? DEREF(bootstrap)[mem_bi].lum * div
                                     : DEREF(block_sum)[mem_bi])
                : 0;
    // Traverse from leafs to root (Reduction)
    uint stride = 1;
    for (uint d = gl_WorkGroupSize.x; d > 0; d >>= 1) {
        memoryBarrierShared();
        barrier();
        uint bi = 0;
        float sum = 0;
        if (tid < d) {
            uint ai = 2 * stride * tid + stride - 1;
            bi = ai + stride;
            ai += CONFLICT_FREE_OFFSET(ai);
            bi += CONFLICT_FREE_OFFSET(bi);
            sum = s_data[bi] + s_data[ai];
        }
        memoryBarrierShared();
        barrier();
        if (tid < d) {
            s_data[bi] = sum;
        }
        stride *= 2;
    }
    uint block_idx = pc.block_idx == 0 ? gl_WorkGroupID.x : pc.block_idx;

    // Zero out the last element and store the sum
    if (tid == 0) {
        uint idx = (gl_WorkGroupSize.x << 1) - 1;
        idx += CONFLICT_FREE_OFFSET(idx);
        if (pc.store_sum == 1) {
            DEREF(block_sum)[block_idx] = s_data[idx];
        }
        s_data[idx] = 0;
    }
    // Traverse from root to leaf
    for (uint d = 1; d <= gl_WorkGroupSize.x; d *= 2) {
        stride >>= 1;
        memoryBarrierShared();
        barrier();
        uint ai = 0;
        uint bi = 0;
        float left = 0;
        float right = 0;
        if (tid < d) {
            ai = 2 * stride * tid + stride - 1;
            bi = ai + stride;
            ai += CONFLICT_FREE_OFFSET(ai);
            bi += CONFLICT_FREE_OFFSET(bi);
            left = s_data[ai];
            right = s_data[bi];
        }
        memoryBarrierShared();
        barrier();
        if (tid < d) {
            s_data[ai] = right;
            s_data[bi] = right + left;
        }
    }
    // Write into device memory
    memoryBarrierShared();
    barrier();
    if (valid_a) {
        if (pc.scan_sums == 0) {
            DEREF(cdf)[mem_ai] = s_data[ai + bank_offset_a];
        } else {
            DEREF(block_sum)[mem_ai] = s_data[ai + bank_offset_a];
        }
    }
    if (valid_b) {
        if (pc.scan_sums == 0) {
            DEREF(cdf)[mem_bi] = s_data[bi + bank_offset_b];
        } else {
            DEREF(block_sum)[mem_bi] = s_data[bi + bank_offset_b];
        }
    }
}
