#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable
#include "../../bda.glsl"
#include "pssmlt_commons.h"
#include "../../utils.glsl"
layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(push_constant) uniform _PushConstantRay { PCMLT pc; };
layout(constant_id = 0) const int NUM_MLT_THREADS = 0;
SCENE_BUFFER(bootstrap, BootstrapSample);
SCENE_BUFFER(seeds, SeedData);
SCENE_BUFFER(cdf, float);
uvec4 seed =
    init_rng(gl_GlobalInvocationID.xy, gl_NumWorkGroups.xy *uvec2(32, 1),
             pc.frame_num ^ pc.random_num);
uint binary_search_cdf(float random_float) {
   uint l = 0;
    uint r = pc.num_bootstrap_samples;
    uint lum_idx = -1;
    uint len = r - l;
    uint first = 0;
    while(len > 0) {
        uint hlf = len >> 1;
        uint middle = first + hlf;
        if(DEREF(cdf)[middle] <= random_float) {
            first = middle + 1;
            len -= hlf + 1;
        } else {
            len = hlf;
        }
    }
    return clamp(first - 1, 0, pc.num_bootstrap_samples -2);
    uint result = lum_idx;
    if (lum_idx > 0) {
        while (result > 0 && DEREF(bootstrap)[result].lum == 0) {
            result--;
        }
    }

    return result;
}
void main() {
    uint idx = gl_GlobalInvocationID.x;
    if(idx >= NUM_MLT_THREADS) {
        return;
    }
    float random_float = rand(seed);
    uint lum_idx = binary_search_cdf(random_float);
    DEREF(seeds)[idx].chain_seed = DEREF(bootstrap)[lum_idx].seed;
}
