#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable

#include "../../bda.glsl"
#include "../../atomic_rgb.glsl"
#include "vcmmlt_commons.h"
#include "../../utils.glsl"

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0, rgba32f) uniform image2D image;
layout(binding = 1) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(push_constant) uniform _PushConstantRay { PCMLT pc; };
SCENE_BUFFER(color_storage, float);
SCENE_BUFFER(mlt_col, float);
void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.x / pc.height,
                         gl_GlobalInvocationID.x % pc.height);
    vec3 col = vec3(0);
    if (pc.mutation_count > 0) {
        const float mutations_per_pixel = float(pc.mutation_count) *
            float(pc.num_mlt_threads) / float(pc.width * pc.height);
        col = RGB_BUFFER_LOAD(mlt_col, gl_GlobalInvocationID.x) / mutations_per_pixel;
    }
    col += RGB_BUFFER_LOAD(color_storage, gl_GlobalInvocationID.x);
    RGB_BUFFER_STORE(mlt_col, gl_GlobalInvocationID.x, vec3(0));
    RGB_BUFFER_STORE(color_storage, gl_GlobalInvocationID.x, vec3(0));
    if (pc.enable_accumulation == 1 && pc.frame_num > 0) {
        float w = 1. / float(pc.frame_num + 1);

        vec3 old_col = imageLoad(image, ivec2(coords)).xyz;
        imageStore(image, ivec2(coords), vec4(mix(old_col, col, w), 1.f));
    } else {
        imageStore(image, ivec2(coords), vec4(col, 1.f));
    }
}
