#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable

#include "../../bda.glsl"
#include "vcmmlt_commons.h"
#include "../../utils.glsl"

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0, rgba32f) uniform image2D image;
layout(binding = 1) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(push_constant) uniform _PushConstantRay { PCMLT pc; };
SCENE_BUFFER(chain_stats, ChainData);
SCENE_BUFFER(color_storage, vec3);
SCENE_BUFFER(mlt_col, vec3);
SCENE_BUFFER_SCALAR(cdf_sum, float);
void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.x / pc.height,
                         gl_GlobalInvocationID.x % pc.height);
    vec3 col = vec3(0);
    float mut_factor = pc.width * pc.height / pc.num_mlt_threads;
    float mult_factor =  1. / (2 * mut_factor * 2);
    for (int i = 0; i < 2; i++) {
        float factor =
            DEREF(chain_stats)[i].normalization /
            (pc.mutations_per_pixel);
        col +=  DEREF(mlt_col)[gl_GlobalInvocationID.x] * factor;
        // col += DEREF(mlt_col)[gl_GlobalInvocationID.x] * DEREF(cdf_sum) /
        //        (pc.mutations_per_pixel);
        // col += 0.5 * DEREF(mlt_col)[gl_GlobalInvocationID.x] *
        //        DEREF(chain_stats)[i].normalization * pc.width * pc.height /
        //        (DEREF(chain_stats)[i].total_samples);
    }
    col += DEREF(color_storage)[gl_GlobalInvocationID.x];
    DEREF(mlt_col)[gl_GlobalInvocationID.x] = vec3(0);
    DEREF(color_storage)[gl_GlobalInvocationID.x] = vec3(0);
    if (pc.enable_accumulation == 1 && pc.frame_num > 0) {
        float w = 1. / float(pc.frame_num + 1);

        vec3 old_col = imageLoad(image, ivec2(coords)).xyz;
        imageStore(image, ivec2(coords), vec4(mix(old_col, col, w), 1.f));
    } else {
        imageStore(image, ivec2(coords), vec4(col, 1.f));
    }
}
