#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable

#include "../../bda.glsl"
#include "vcmmlt_commons.h"
#include "../../utils.glsl"

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(push_constant) uniform _PushConstantRay { PCMLT pc; };
layout(constant_id = 0) const int MODE = 0;
uint size = pc.num_mlt_threads;
SCENE_BUFFER(residual, SumData);
SCENE_BUFFER_SCALAR(counter, int);
SCENE_BUFFER(chain_stats, ChainData);
shared vec2 dataf[32];
shared uint datau[32];
void main() {
    uint idx = gl_GlobalInvocationID.x;
    vec2 valf;
    uint valu;
    uint limit = DEREF(counter) == 0 ? size : ((size + 1023) >> (10 * DEREF(counter)));
    if (idx >= limit) {
        dataf[gl_SubgroupInvocationID] = vec2(0);
        datau[gl_SubgroupInvocationID] = 0;
        return;
    }
    valf = vec2(DEREF(residual)[idx].x, DEREF(residual)[idx].z);
    valu = DEREF(residual)[idx].y;
    memoryBarrier();
    barrier();

    valf = subgroupAdd(valf);
    valu = subgroupAdd(valu);
    if (gl_SubgroupInvocationID == 0) {
        dataf[gl_SubgroupID] = valf;
        datau[gl_SubgroupID] = valu;
    }
    barrier();

    if (gl_SubgroupID == 0) {
        valf = dataf[gl_SubgroupInvocationID];
        valu = datau[gl_SubgroupInvocationID];
        subgroupBarrier();
        valf = subgroupAdd(valf);
        valu = subgroupAdd(valu);
    }
    if (gl_LocalInvocationID.x == 0) {
        DEREF(residual)[gl_WorkGroupID.x].x = valf.x;
        DEREF(residual)[gl_WorkGroupID.x].y = valu;
        DEREF(residual)[gl_WorkGroupID.x].z = valf.y;
    }
    if (idx == 0) {
        DEREF(counter) += 1;
    }
    if (idx == 0) {
        DEREF(chain_stats)[MODE].total_luminance += valf.x;
        DEREF(chain_stats)[MODE].lum_samples += valu;
        DEREF(chain_stats)[MODE].total_samples += valf.y;
    }
}
