#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

#include "../../bda.glsl"
#include "ddgi_commons.h"
#include "ddgi_commons.glsl"

#define WG_SIZE 32
layout(local_size_x = WG_SIZE, local_size_y = WG_SIZE, local_size_z = 1) in;

layout(binding = 0) uniform _SceneUBO { SceneUBO ubo; };
layout(binding = 1) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(binding = 2, rgba16f) uniform image2D irr_output_img;

layout(binding = 3) uniform sampler2D irr_img;
layout(binding = 4) uniform sampler2D depth_img;

layout(binding = 5) uniform _DDGIUniforms { DDGIUniforms ddgi_uniforms; };
layout(binding = 6, rgba32f) uniform image2D image;

layout(push_constant) uniform _PushConstantRay { PCDDGI pc; };
SCENE_BUFFER(probe_offsets, vec4);
SCENE_BUFFER(direct_lighting, vec3);
SCENE_BUFFER(g_buffer, GBufferData);

#include "../../surface.glsl"

#include "ddgi_irradiance.glsl"

void store_output(ivec2 coords, vec3 col) {
	if (pc.enable_accumulation == 1 && pc.frame_num > 0) {
		const float weight = 1.0 / float(pc.frame_num + 1);
		col = mix(imageLoad(image, coords).xyz, col, weight);
	}
	imageStore(image, coords, vec4(col, 1.0));
}

void main() {
	ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
	if (coords.x >= pc.width || coords.y >= pc.height) {
		return;
	}
	const vec2 pixel_center = vec2(coords) + vec2(0.5);
	const int linear_idx = int(gl_GlobalInvocationID.x * pc.height + gl_GlobalInvocationID.y);
	uint idx = pc.height * gl_GlobalInvocationID.x + gl_GlobalInvocationID.y;
	vec3 col = pc.direct_lighting == 1 ? DEREF(direct_lighting)[idx] : vec3(0);
	const SurfaceRef surface_ref = DEREF(g_buffer)[linear_idx].surface;
	if (!surface_ref_valid(surface_ref)) {
		store_output(coords, col);
		return;
	}
	const SurfaceData surface = load_surface(surface_ref);
	vec3 n_s = surface.n_s;
	vec3 n_g = surface.n_g;
	vec3 wo = normalize((ubo.inv_view * vec4(0, 0, 0, 1)).xyz - surface.pos);
	face_forward(n_s, n_g, wo);
	vec3 irradiance = sample_irradiance(surface.pos, n_s, wo);
	col += DEREF(g_buffer)[idx].albedo / PI * irradiance;
	store_output(coords, col);
	imageStore(irr_output_img, coords, vec4(irradiance, 1.0f));
}
