#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable
#include "../commons.h"
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0) readonly buffer RTUtilsDesc_ { RTUtilsDesc post_desc; };
layout(push_constant) uniform PC { RTUtilsPC pc; };
#include "../bda.glsl"
DESC_BUFFER_RO(post_desc, gt_img, vec4);
DESC_BUFFER_RO(post_desc, out_img, vec4);
DESC_BUFFER(post_desc, residual, float);
DESC_BUFFER_SCALAR(post_desc, rmse_val, float);

void main() {
  float rmse = sqrt(DEREF(residual)[0]) / (pc.size * 3);
  DEREF(rmse_val) = rmse;
}