#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

#define BDPT_RNG_STREAM_SALT 0x74F4AF41u
#include "bdpt_pass_commons.glsl"

void main() {
	DEREF(path_cnt)[pixel_idx].light_vertex_count =
		uint(bdpt_generate_light_subpath(pc.max_depth + 1));
}
