#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

#define BDPT_RNG_STREAM_SALT 0x8F9E9875u
#include "bdpt_pass_commons.glsl"

void main() {
	const vec2 pixel = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
	const vec2 d = pixel / vec2(gl_LaunchSizeEXT.xy) * 2.0 - 1.0;
	const vec3 origin = vec3(ubo.inv_view * vec4(0, 0, 0, 1));

	vec4 area_int = ubo.inv_projection *
		vec4(2.0 / gl_LaunchSizeEXT.x, 2.0 / gl_LaunchSizeEXT.y, 0, 1);
	area_int /= area_int.w;
	const float cam_area = abs(area_int.x * area_int.y);

	DEREF(path_cnt)[pixel_idx].eye_vertex_count = uint(
		bdpt_generate_camera_subpath(d, origin, pc.max_depth + 1, cam_area));
}
