#version 460
#extension GL_EXT_ray_query : require
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#define SCENE_TEX_IDX 10
#include "../../../bda.glsl"
#include "pm_commons.glsl"
layout(set = 1, binding = 1) uniform accelerationStructureEXT photon_bvh;

layout(binding = 4, rgba16) writeonly uniform image2D canonical_contributions_tex;
layout(binding = 5, rgba32f) uniform image2D caustics_texture;
layout(binding = 6, std430) readonly buffer PrevPhotonReservoirs { PhotonReservoir in_reservoirs[]; };
layout(binding = 7, std430) writeonly buffer CurrPhotonReservoirs { PhotonReservoir out_reservoirs[]; };
layout(binding = 8, std430) readonly buffer PrevPhotonData { PhotonData prev_photon_eye[]; };
layout(binding = 9, std430) readonly buffer CurrPhotonData { PhotonData photon_eye_data[]; };
SCENE_BUFFER(caustic_photon_aabbs, PhotonAABB);
SCENE_BUFFER(caustic_photon_light, PhotonData);
SCENE_BUFFER_SCALAR(photon_count, uint);

uvec4 seed = init_rng(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy, pc.seed2);
uvec4 sampling_seed = init_rng(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy, pc.sampling_seed);

void main() {
	PhotonData photon_eye = photon_eye_data[pixel_idx];
	PhotonReservoir reservoir;
	init_reservoir(reservoir);

	vec3 col = vec3(0);
	if (photon_data_valid(photon_eye)) {
		HitData cam_gbuffer = get_hitdata(photon_eye.barycentrics, photon_eye.primitive_instance_id.y,
										  photon_eye.primitive_instance_id.x);
		Material cam_hit_mat = load_material(cam_gbuffer.material_idx, cam_gbuffer.uv);
		ASSERT(is_rough(cam_hit_mat));

		rayQueryEXT ray_query;

		uint ray_flags = 0;
		rayQueryInitializeEXT(ray_query, photon_bvh, ray_flags, 0xFF, cam_gbuffer.pos, 0, cam_gbuffer.n_s, 1e-8);

		bool traverse = true;
		int counter = 0;

		vec3 phi = vec3(0);

		PhotonReservoir canonical_reservoir;
		init_reservoir(canonical_reservoir);

		vec3 selected_contribution = vec3(0);
		vec3 wo = from_spherical(photon_eye.dir);

		bool eye_side;
		uint eye_path_length;
		unpack_photon_flags(photon_eye.flags, eye_side, eye_path_length);

		while (traverse) {
			traverse = rayQueryProceedEXT(ray_query);
			if (!traverse) {
				break;
			}

			int photon_idx = rayQueryGetIntersectionPrimitiveIndexEXT(ray_query, false);
			PhotonData photon_light = DEREF(caustic_photon_light)[photon_idx];

			HitData photon_gbuffer = get_hitdata(photon_light.barycentrics, photon_light.primitive_instance_id.y,
												 photon_light.primitive_instance_id.x);

			bool unused;
			uint photon_path_length;

			unpack_photon_flags(photon_light.flags, unused, photon_path_length);

			vec3 wi = from_spherical(photon_light.dir);
			if (!is_photon_valid(cam_gbuffer, photon_gbuffer, wi, eye_path_length, photon_path_length)) {
				continue;
			}

			float cam_pdf_fwd;
			float cam_pdf_rev;
			vec3 f = eval_bsdf(cam_gbuffer.n_s, cam_gbuffer.n_g, wo, cam_hit_mat, TRANSPORT_MODE_FROM_CAMERA,
							   eye_side, wi,
							   cam_pdf_fwd, cam_pdf_rev);

			float mis_weight = 1.0 / (1.0 + photon_light.d_vm * cam_pdf_fwd);

			ASSERT(mis_weight >= 0);
			ASSERT(!isnan(mis_weight));

			vec3 contribution = mis_weight * f * photon_light.throughput * photon_eye.throughput;

			ASSERT(!isnan(photon_light.d_vm));
			bool merged =
				stream_photon_reservoir(seed, canonical_reservoir, photon_light.throughput, photon_light.barycentrics,
										photon_light.primitive_instance_id, photon_light.dir, photon_light.d_vm,
										calc_target_pdf(contribution), 1.0);
			if (merged) {
				selected_contribution = contribution;
			}
			phi += contribution;
			counter++;
		}

		canonical_reservoir.M = 1;
		// Works because M == 1
		calc_photon_reservoir_W_with_mis(canonical_reservoir);

		float m_c = 1.0;
		bool temp_accepted = false;
		vec3 canonical_contribution = selected_contribution;
		// Start from 3rd frame onwards because on 2nd frame we've just started collecting
		if (pc.pm_temporal_reuse == 1 && pc.total_frame_num > 1) {
			// Temporal reuse
			vec4 prev_pos = ubo.prev_view * vec4(cam_gbuffer.pos, 1);
			prev_pos /= prev_pos.z;
			prev_pos = -ubo.prev_projection * prev_pos;
			ivec2 prev_coords = ivec2(0.5 * (1 + prev_pos.xy) * gl_LaunchSizeEXT.xy);

			if (!(any(lessThan(prev_coords, ivec2(0))) || any(greaterThanEqual(prev_coords, gl_LaunchSizeEXT.xy)))) {
				PhotonData prev_photon_eye = prev_photon_eye[prev_coords.x * pc.height + prev_coords.y];
				PhotonReservoir prev_reservoir = in_reservoirs[prev_coords.x * pc.height + prev_coords.y];
				// Always true as long as pc.total_frame_num > 1
				if (photon_reservoir_data_valid(prev_reservoir)) {
					ASSERT(photon_data_valid(prev_photon_eye));
					HitData prev_photon_gbuffer =
						get_hitdata(prev_reservoir.barycentrics, prev_reservoir.primitive_instance_id.y,
									prev_reservoir.primitive_instance_id.x);
					vec3 wi_prev = from_spherical(prev_reservoir.wi);

					float cam_pdf_fwd_temp;
					float cam_pdf_rev_temp;
					vec3 f_temp = eval_bsdf(cam_gbuffer.n_s, cam_gbuffer.n_g, wo, cam_hit_mat,
										 TRANSPORT_MODE_FROM_CAMERA, eye_side, wi_prev, cam_pdf_fwd_temp,
											cam_pdf_rev_temp);
					float mis_weight_temp = 1.0 / (1.0 + prev_reservoir.d_vm * cam_pdf_fwd_temp);
					vec3 temp_contribution = mis_weight_temp * f_temp * prev_reservoir.flux * photon_eye.throughput;

					prev_reservoir.M = min(20, prev_reservoir.M);

					bool unused;
					uint prev_photon_path_length;

					unpack_photon_flags(prev_reservoir.flags, unused, prev_photon_path_length);

					float target_pdf;
					if (!is_photon_valid(cam_gbuffer, prev_photon_gbuffer, wi_prev, eye_path_length,
										 prev_photon_path_length)) {
						target_pdf = 0;
					} else {
						target_pdf = calc_target_pdf(temp_contribution);
					}

					float m_i_num = prev_reservoir.M * prev_reservoir.target_pdf;
					float m_i_denom = m_i_num + target_pdf;
					float m_i = m_i_denom == 0.0 ? 0.0 : m_i_num / m_i_denom;

					temp_accepted = combine_reservoir(seed, reservoir, prev_reservoir, target_pdf, m_i);
					if (temp_accepted) {
						selected_contribution = temp_contribution;
					}
					ASSERT(!isnan(m_i));

					// Bias correction
					if (photon_reservoir_data_valid(canonical_reservoir)) {
						HitData prev_cam_gbuffer =
							get_hitdata(prev_photon_eye.barycentrics, prev_photon_eye.primitive_instance_id.y,
										prev_photon_eye.primitive_instance_id.x);
						Material prev_cam_hit_mat = load_material(prev_cam_gbuffer.material_idx, prev_cam_gbuffer.uv);
						vec3 wo_prev = from_spherical(prev_photon_eye.dir);
						vec3 wi = from_spherical(canonical_reservoir.wi);

						bool eye_side_prev;
						uint eye_path_length_prev;
						unpack_photon_flags(prev_photon_eye.flags, eye_side_prev, eye_path_length_prev);

						float cam_pdf_fwd_prev;
						float cam_pdf_rev_prev;
						vec3 f_prev = eval_bsdf(prev_cam_gbuffer.n_s, prev_cam_gbuffer.n_g, wo_prev, prev_cam_hit_mat,
										   TRANSPORT_MODE_FROM_CAMERA, eye_side_prev, wi,
												cam_pdf_fwd_prev, cam_pdf_rev_prev);

						float mis_weight_prev = 1.0 / (1.0 + canonical_reservoir.d_vm * cam_pdf_fwd_prev);
						vec3 prev_contribution =
							mis_weight_prev * f_prev * canonical_reservoir.flux * prev_photon_eye.throughput;

						HitData canonical_photon_gbuffer =
							get_hitdata(canonical_reservoir.barycentrics, canonical_reservoir.primitive_instance_id.y,
										canonical_reservoir.primitive_instance_id.x);
						uint canonical_photon_path_length;
						unpack_photon_flags(canonical_reservoir.flags, unused, canonical_photon_path_length);
						float target_pdf_in_neighbor;
						if (!is_photon_valid(prev_cam_gbuffer, canonical_photon_gbuffer, wi, eye_path_length_prev,
											 canonical_photon_path_length)) {
							target_pdf_in_neighbor = 0;
						} else {
							target_pdf_in_neighbor = calc_target_pdf(prev_contribution);
						}
						ASSERT(!isnan(target_pdf_in_neighbor));
						float m_c_num = prev_reservoir.M * target_pdf_in_neighbor;
						float m_c_denom = m_c_num + canonical_reservoir.target_pdf;
						float m_c_val = m_c_denom == 0.0 ? 0.0 : m_c_num / m_c_denom;
						if (m_c_val > 0) {
							m_c -= m_c_val;
						}
					}
				}
			}
		}

		ASSERT(!isnan(m_c));
		LOG_CLICKED("m_c: %f\n", m_c);
		bool canonical_accepted =
			combine_reservoir(seed, reservoir, canonical_reservoir, canonical_reservoir.target_pdf, m_c);
		if (canonical_accepted) {
			selected_contribution = canonical_contribution;
		}

		calc_photon_reservoir_W_with_mis(reservoir);

		phi = reservoir.W * selected_contribution;
		phi /= (PI * pc.photon_radius * pc.photon_radius * pc.num_photons);

		if (isnan(phi.x) || isnan(phi.y) || isnan(phi.z)) {
			phi = vec3(0);
		}
		col = phi;
	}
	out_reservoirs[pixel_idx] = reservoir;
	imageStore(caustics_texture, ivec2(gl_LaunchIDEXT.xy), vec4(col, 1.f));
}
