#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#include "../../../bda.glsl"
#include "gris_commons.glsl"

SCENE_BUFFER(caustic_photon_light, PhotonData);
SCENE_BUFFER(caustic_photon_aabbs, PhotonAABB);
SCENE_BUFFER_SCALAR(photon_count, uint);

uvec4 seed = init_rng(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy, pc.seed2);

void main() {
	vec4 rands_pos = rand4(seed);
	vec2 rands_dir = rand2(seed);

	const LightLeSample light_sample = sample_light_Le(rands_pos, rands_dir, pc.num_lights);
	if (light_sample.pdf_joint <= 0.0) {
		return;
	}
	vec3 wi = light_sample.wi;
	vec3 pos = light_sample.position;
	vec3 throughput = light_sample.Le * light_sample.cos_from_light / light_sample.pdf_joint;

	float eta_vm = PI * pc.photon_radius * pc.photon_radius * pc.num_photons;
	float d_vm_common = light_sample.pdf_direction_w == 0
						? 0
						: 1.0 / (light_sample.pdf_direction_w * eta_vm);
	float d_vm_nee = light_sample.selection_pmf;
	float d_vm_bsdf = light_sample.selection_pmf / light_sample.pdf_position_a;

	bool finite = is_light_finite(light_sample.flags);

	if (!is_light_delta(light_sample.flags)) {
		d_vm_bsdf *= (finite ? light_sample.cos_from_light : 1.0);
	} else {
		d_vm_bsdf = 0;
	}

	bool last_specular = false;
	for (int d = 0; d < pc.max_depth; d++) {
		traceRayEXT(tlas, flags, 0xFF, 0, 0, 0, pos, tmin, wi, tmax, 0);
		bool found_isect = payload.instance_idx != -1;
		if (!found_isect) {
			break;
		}

		HitData gbuffer = get_hitdata(payload.attribs, payload.instance_idx, payload.triangle_idx);

		vec3 to_prev = pos - gbuffer.pos;
		float dist_sqr = dot(to_prev, to_prev);
		to_prev /= sqrt(dist_sqr);
		float cos_theta_wo = abs(dot(wi, gbuffer.n_s));

		d_vm_common = cos_theta_wo > 0 ? d_vm_common / cos_theta_wo : 0;
		if(d == 0) {
			d_vm_nee *= dist_sqr;
		}

		const vec3 wo = -wi;
		vec3 n_s = gbuffer.n_s;
		vec3 n_g = gbuffer.n_g;
		bool side = face_forward(n_s, n_g, wo);

		float cos_wo = dot(wo, n_s);
		Material hit_mat = load_material(gbuffer.material_idx, gbuffer.uv);

		if (is_rough(hit_mat) && last_specular) {
			uint photon_idx = atomicAdd(DEREF(photon_count), 1);
			DEREF(caustic_photon_aabbs)[photon_idx].min = gbuffer.pos - pc.photon_radius;
			DEREF(caustic_photon_aabbs)[photon_idx].max = gbuffer.pos + pc.photon_radius;

			DEREF(caustic_photon_light)[photon_idx].barycentrics = payload.attribs;
			DEREF(caustic_photon_light)[photon_idx].primitive_instance_id = uvec2(payload.triangle_idx, payload.instance_idx);
			DEREF(caustic_photon_light)[photon_idx].dir = to_spherical(wo);
			DEREF(caustic_photon_light)[photon_idx].throughput = throughput;
			// side is not used
			// Path length = Num of edges from light
			DEREF(caustic_photon_light)[photon_idx].flags = pack_photon_flags(side, d + 1);
#ifdef DISABLE_PM_MIS
			DEREF(caustic_photon_light)[photon_idx].d_vm = 0;
#else
			float d_vm = (d_vm_bsdf + d_vm_nee) * d_vm_common;
			DEREF(caustic_photon_light)[photon_idx].d_vm = d_vm;
			ASSERT(d_vm >= 0);
#endif // DISABLE_PM_MIS
		}
		last_specular = !is_rough(hit_mat);
		pos = offset_ray(gbuffer.pos, n_g);
		float pdf_dir, cos_theta;
		const vec3 f = sample_bsdf(n_s, wo, hit_mat, 0, side, wi, pdf_dir, cos_theta, seed);
		float abs_cos_theta = abs(cos_theta);
		throughput *= f * abs_cos_theta / pdf_dir;

		bool is_specular = (hit_mat.bsdf_props & BSDF_FLAG_SPECULAR) != 0;
		d_vm_common *= abs_cos_theta;
		if (!is_specular) {
			// TODO: Is side correct here?
			float pdf_rev = bsdf_pdf(hit_mat, n_s, wi, wo, side);
			// pdf_rev / pdf_fwd
			if(d == 0) {
				d_vm_nee /= pdf_rev;
			}
			d_vm_common *= pdf_rev / pdf_dir;
		} else if(d == 0 ) {
			d_vm_nee = 0;
		}

		if (f == vec3(0) || pdf_dir == 0) {
			break;
		}
		if (d > RR_MIN_DEPTH) {
			float rr_prob = min(0.95f, luminance(throughput));
			if (rr_prob < rand(seed))
				break;
			else
				throughput /= rr_prob;
		}
	}
}
