#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable
#include "../../bda.glsl"
#include "vcm_commons.h"
#include "../../utils.glsl"
layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(push_constant) uniform _PushConstantRay { PCVCM pc; };

uint size = pc.width * pc.height;

SCENE_BUFFER(light_samples, VCMRestirData);
SCENE_BUFFER(vcm_reservoir, VCMReservoir);

void init_reservoir(out VCMReservoir r_new) {
    r_new.w_sum = 0;
    r_new.W = 0;
    r_new.m = 0;
}

void main() {
    if(gl_GlobalInvocationID.x >= size) {
        return;
    }
    VCMReservoir r_new;
    init_reservoir(r_new);
    r_new.sample_idx = -1;
    DEREF(vcm_reservoir)[gl_GlobalInvocationID.x] = r_new;
}
