#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

#include "../../bda.glsl"
#include "vcm_commons.h"
#include "../../commons.glsl"
layout(location = 0) rayPayloadEXT HitPayload payload;
layout(location = 1) rayPayloadEXT AnyHitPayload any_hit_payload;
#include "../../shadow_ray.glsl"

layout(push_constant) uniform _PushConstantRay { PCVCM pc; };
// VCM buffers

SCENE_BUFFER(light_samples, VCMRestirData);
SCENE_BUFFER_SCALAR(should_resample, uint);

SCENE_BUFFER(vcm_reservoir, VCMReservoir);

SCENE_BUFFER_SCALAR(avg, AvgStruct);

uint screen_size = gl_LaunchSizeEXT.x * gl_LaunchSizeEXT.y;
const uint flags = gl_RayFlagsOpaqueEXT;
const float tmin = 0.001;
const float tmax = 10000.0;
#define RR_MIN_DEPTH 3
uint pixel_idx = (gl_LaunchIDEXT.x * gl_LaunchSizeEXT.y + gl_LaunchIDEXT.y);
uvec4 seed = init_rng(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy,
                      pc.random_num);
uint vcm_light_path_idx =
    (gl_LaunchIDEXT.x * gl_LaunchSizeEXT.y + gl_LaunchIDEXT.y) *
    (pc.max_depth);

const uint FRAME_INTERVAL = 10;

uint restir_hash(ivec3 p, uint size) {
    return uint((p.x * 73856093) ^ (p.y * 19349663) ^ p.z * 83492791) % size;
}

vec3 normalize_grid(vec3 p, vec3 min_bnds, vec3 max_bnds) {
    return (p - min_bnds) / (max_bnds - min_bnds);
}

ivec3 get_grid_idx(vec3 p, vec3 min_bnds, vec3 max_bnds, ivec3 grid_res) {
    ivec3 res = ivec3(normalize_grid(p, min_bnds, max_bnds) * grid_res);
    clamp(res, vec3(0), grid_res - vec3(1));
    return res;
}

vec3 vcm_connect_cam(const vec3 cam_pos, const vec3 cam_nrm, const vec3 n_s,
                     const vec3 n_g,
                     const float cam_A, const vec3 pos, const in VCMState state,
                     const float eta_vm, const vec3 wo, const Material mat,
                     out ivec2 coords) {
    vec3 L = vec3(0);
    vec3 dir = cam_pos - pos;
    float len = length(dir);
    dir /= len;
    float cos_y = dot(dir, n_g);
    float cos_theta = dot(cam_nrm, -dir);
    if (cos_theta <= 0.) {
        return L;
    }

    // pdf_rev / pdf_fwd
    // in the case of light coming to camera
    // simplifies to abs(cos(theta)) / (A * cos^3(theta) * len^2)
    float cos_3_theta = cos_theta * cos_theta * cos_theta;
    const float cam_pdf_ratio = abs(cos_y) / (cam_A * cos_3_theta * len * len);
    vec3 ray_origin = offset_ray(pos, n_g, dot(dir, n_g) < 0.0);
    float pdf_rev, pdf_fwd;
    const vec3 f = eval_bsdf(n_s, n_g, wo, mat, TRANSPORT_MODE_FROM_LIGHT,
                             dot(payload.n_s, wo) > 0, dir, pdf_fwd, pdf_rev);
    if (f == vec3(0)) {
        return L;
    }
    if (cam_pdf_ratio > 0.0) {
        if (!connection_occluded(ray_origin, dir, len, 0xFF)) {
            const float w_light = (cam_pdf_ratio / (screen_size)) *
                                  (eta_vm + state.d_vcm + pdf_rev * state.d_vc);
            const float mis_weight = 1. / (1. + w_light);
            // We / pdf_we * abs(cos_theta) = cam_pdf_ratio
            L = mis_weight * state.throughput * cam_pdf_ratio * f / screen_size;
        }
    }
    dir = -dir;
    vec4 target = ubo.view * vec4(dir.x, dir.y, dir.z, 0);
    target /= target.z;
    target = -ubo.projection * target;
    coords = ivec2(0.5 * (1 + target.xy) * gl_LaunchSizeEXT.xy - 0.5);
    if (coords.x < 0 || coords.x >= gl_LaunchSizeEXT.x || coords.y < 0 ||
        coords.y >= gl_LaunchSizeEXT.y || dot(dir, cam_nrm) < 0) {
        return vec3(0);
    }
    return L;
}

uint get_restir_hash_idx(uint light_idx, float u, float v) {
    const int base_res =
        max(1, int(sqrt(float(screen_size) / pc.num_lights)));
    ivec3 grid_res = ivec3(pc.num_lights, base_res, base_res);
    ivec3 grid_idx =
        get_grid_idx(vec3(light_idx, u, v), vec3(0, 0, 0),
                     vec3(pc.num_lights, 1, 1), grid_res);

    return restir_hash(grid_idx, screen_size);
}

bool vcm_generate_light_sample(float eta_vc, out VCMState light_state,
                               inout VCMRestirData s, out float pdf_o) {
    const vec4 xi_position = rand4(seed);
    const vec2 xi_direction = rand2(seed);
    const LightLeSample light_sample =
        sample_light_Le(xi_position, xi_direction, pc.num_lights);
    if (light_sample.pdf_joint <= EPS) {
        return false;
    }
    light_state.pos = light_sample.position;
    light_state.n_s = light_sample.normal;
    light_state.area = 1.0 / light_sample.pdf_position_a;
    light_state.wi = light_sample.wi;
    light_state.throughput = light_sample.Le * light_sample.cos_from_light /
                             light_sample.pdf_joint;
    light_state.d_vcm = 1.0 / light_sample.pdf_direction_w;
    light_state.d_vc = is_light_delta(light_sample.flags)
                           ? 0.0
                           : light_sample.cos_from_light / light_sample.pdf_joint;
    light_state.d_vm = light_state.d_vc * eta_vc;
    vec2 canonical_uv = light_sample.identity.bary;
    const uint light_type = get_light_type(light_sample.flags);
    if (light_type == LIGHT_POINT || light_type == LIGHT_SPOT) {
        canonical_uv = xi_direction;
    } else if (light_type == LIGHT_DIRECTIONAL) {
        canonical_uv = xi_position.yz;
    }
    s.dir = light_sample.wi;
    s.hash_idx = get_restir_hash_idx(light_sample.identity.light_idx,
                                     canonical_uv.x, canonical_uv.y);
    s.pdf_dir = light_sample.pdf_direction_w;
    pdf_o = light_sample.pdf_direction_w;
    return true;
}

void main() {
    if (DEREF(should_resample) != 0) {
        return;
    }
    if (pixel_idx == 0) {
        if(pc.frame_num == 0) {
            DEREF(avg).avg = 0;
            DEREF(avg).prev = 0;
        } else {
            DEREF(avg).avg = 0.6 * DEREF(avg).avg + 0.4 * (pc.frame_num - DEREF(avg).prev);
            DEREF(avg).prev = pc.frame_num;
            //debugPrintfEXT("resampling %d, avg: %f\n", pc.total_frame_num, DEREF(avg).avg);
        }
    }

    const vec2 pixel = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 in_uv = pixel / vec2(gl_LaunchSizeEXT.xy);
    vec2 d = in_uv * 2.0 - 1.0;
    vec4 origin = ubo.inv_view * vec4(0, 0, 0, 1);
    vec4 target = ubo.inv_projection * vec4(d.x, d.y, 1, 1);
    vec3 direction = vec3(sample_camera(d));
    float total_lum = 0;
    vec4 area_int = (ubo.inv_projection * vec4(2. / gl_LaunchSizeEXT.x,
                                               2. / gl_LaunchSizeEXT.y, 0, 1));
    area_int /= (area_int.w);
    const float cam_area = abs(area_int.x * area_int.y);
    VCMRestirData s;
    float pdf_o;
    const float radius = pc.radius;
    const float radius_sqr = radius * radius;
    float eta_vcm = PI * radius_sqr * screen_size;
    float eta_vc = (pc.use_vc == 1) ? 1.0 / eta_vcm : 0;
    float eta_vm = (pc.use_vm == 1) ? PI * radius_sqr * screen_size : 0;
    VCMState light_state;
    bool result = vcm_generate_light_sample(eta_vc, light_state, s, pdf_o);
    if (!result) {
        return;
    }

    // Light tracing
    {
        const vec3 cam_pos = origin.xyz;
        const vec3 cam_nrm = vec3(-ubo.inv_view * vec4(0, 0, 1, 0));
        int depth;
        int path_idx = 0;
        for (depth = 1;; depth++) {
            traceRayEXT(tlas, flags, 0xFF, 0, 0, 0, light_state.pos, tmin,
                        light_state.wi, tmax, 0);
            if (payload.material_idx == -1) {
                break;
            }
            vec3 wo = light_state.pos - payload.pos;

            vec3 n_s = payload.n_s;
            float cos_wo = dot(wo, n_s);
            vec3 n_g = payload.n_g;
            bool side = true;
            if (dot(payload.n_g, wo) <= 0.)
                n_g = -n_g;
            if (cos_wo <= 0.) {
                cos_wo = -cos_wo;
                n_s = -n_s;
                side = false;
            }

            if (dot(n_g, wo) * dot(n_s, wo) <= 0) {
                // We dont handle BTDF at the moment
                break;
            }
            float dist = length(payload.pos - light_state.pos);
            float dist_sqr = dist * dist;
            wo /= dist;
            const Material mat =
                load_material(payload.material_idx, payload.uv);
            const bool mat_specular =
                (mat.bsdf_props & BSDF_FLAG_SPECULAR) == BSDF_FLAG_SPECULAR;
            // Complete the missing geometry terms
            const float cos_theta_wo = abs(dot(wo, n_g));
            // Can't connect from specular to camera path, can't merge either
            light_state.d_vcm *= dist_sqr;
            light_state.d_vcm /= cos_theta_wo;
            light_state.d_vc /= cos_theta_wo;
            light_state.d_vm /= cos_theta_wo;
            if (depth >= pc.max_depth + 1) {
                break;
            }
            // Reverse pdf in solid angle form, since we have geometry term
            // at the outer paranthesis
            if (!mat_specular &&
                (pc.use_vc == 1 && depth < pc.max_depth)) {
                // Connect to camera
                ivec2 coords;
                vec3 splat_col = vcm_connect_cam(
                    cam_pos, cam_nrm, n_s, n_g, cam_area, payload.pos,
                    light_state, eta_vm, wo, mat, coords);
                float lum = luminance(splat_col);
                if (lum > 0) {
                    uint idx = coords.x * gl_LaunchSizeEXT.y + coords.y;
                    total_lum += lum;
                }
            }
            // Continue the walk
            float pdf_dir;
            float cos_theta;
            const vec3 f = sample_bsdf(
                n_s, n_g, wo, mat, TRANSPORT_MODE_FROM_LIGHT, side,
                light_state.wi, pdf_dir, cos_theta, seed);
            const bool same_hemisphere =
                same_hemisphere(light_state.wi, wo, n_s);

            const bool mat_transmissive =
                (mat.bsdf_props & BSDF_FLAG_TRANSMISSION) == BSDF_FLAG_TRANSMISSION;
            if (f == vec3(0) || pdf_dir == 0 ||
                (!same_hemisphere && !mat_transmissive)) {
                break;
            }
            float pdf_rev = pdf_dir;
            if (!mat_specular) {
                pdf_rev = bsdf_pdf(mat, n_s, n_g, light_state.wi, wo, side);
            }
            const float abs_cos_theta = abs(cos_theta);
            const float mis_cos_theta = abs(dot(light_state.wi, n_g));

            light_state.pos = offset_ray(payload.pos, n_g);
            // Note, same cancellations also occur here from now on
            // see _vcm_generate_light_sample_
            if (!mat_specular) {
                light_state.d_vc =
                    (mis_cos_theta / pdf_dir) *
                    (eta_vm + light_state.d_vcm + pdf_rev * light_state.d_vc);
                light_state.d_vm = (mis_cos_theta / pdf_dir) *
                                   (1 + light_state.d_vcm * eta_vc +
                                    pdf_rev * light_state.d_vm);
                light_state.d_vcm = 1.0 / pdf_dir;
            } else {
                // Specular pdf has value = inf, so d_vcm = 0;
                light_state.d_vcm = 0;
                // pdf_fwd = pdf_rev = delta -> cancels
                light_state.d_vc *= mis_cos_theta;
                light_state.d_vm *= mis_cos_theta;
            }

            light_state.throughput *= f * abs_cos_theta / pdf_dir;
            light_state.n_s = n_s;
            light_state.area = payload.area;
            light_state.material_idx = payload.material_idx;
        }
    }
    const float p_hat = total_lum;
    //const float p_hat = s.pdf_dir;
    if (p_hat > 0) {
        s.p_hat = p_hat;
        s.valid = 1;
        s.frame_idx = pc.total_frame_num;
        atomicAdd(DEREF(vcm_reservoir)[s.hash_idx].factor, 1);
        DEREF(light_samples)[pixel_idx] = s;
    }
#undef light_vtx
}
