#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

#include "vcm_commons.h"
#include "../../commons.glsl"
layout(location = 0) rayPayloadEXT HitPayload payload;
layout(location = 1) rayPayloadEXT AnyHitPayload any_hit_payload;

layout(push_constant) uniform _PushConstantRay { PCVCM pc; };
// VCM buffers
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer VCMReservoir_ { VCMReservoir d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer ShouldResample { uint d; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer LightStates { LightState d[]; };

ShouldResample should_resample = ShouldResample(scene_desc.should_resample_addr);
LightStates light_states = LightStates(scene_desc.light_state_addr);

VCMReservoir_ temporal_reservoirs = VCMReservoir_(scene_desc.vcm_reservoir_addr);

uint screen_size = gl_LaunchSizeEXT.x * gl_LaunchSizeEXT.y;
const uint flags = gl_RayFlagsOpaqueEXT;
const float tmin = 0.001;
const float tmax = 10000.0;
#define RR_MIN_DEPTH 3
uint pixel_idx = (gl_LaunchIDEXT.x * gl_LaunchSizeEXT.y + gl_LaunchIDEXT.y);
uvec4 seed = init_rng(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy, pc.total_frame_num ^ pc.random_num);
uint vcm_light_path_idx = (gl_LaunchIDEXT.x * gl_LaunchSizeEXT.y + gl_LaunchIDEXT.y) * (pc.max_depth);

const uint FRAME_INTERVAL = 10;

uint restir_hash(ivec3 p, uint size) { return uint((p.x * 73856093) ^ (p.y * 19349663) ^ p.z * 83492791) % size; }

vec3 normalize_grid(vec3 p, vec3 min_bnds, vec3 max_bnds) { return (p - min_bnds) / (max_bnds - min_bnds); }

ivec3 get_grid_idx(vec3 p, vec3 min_bnds, vec3 max_bnds, ivec3 grid_res) {
	ivec3 res = ivec3(normalize_grid(p, min_bnds, max_bnds) * grid_res);
	clamp(res, vec3(0), grid_res - vec3(1));
	return res;
}

uint get_restir_hash_idx(uint light_idx, float u, float v) {
	const int base_res = max(1, int(sqrt(float(screen_size) / pc.num_lights)));
	ivec3 grid_res = ivec3(pc.num_lights, base_res, base_res);
	ivec3 grid_idx = get_grid_idx(vec3(light_idx, u, v), vec3(0, 0, 0), vec3(pc.num_lights, 1, 1), grid_res);
	return restir_hash(grid_idx, screen_size);
}

bool vcm_generate_light_sample(out LightState light_state) {
	const vec4 xi_position = rand4(seed);
	const vec2 xi_direction = rand2(seed);
	const LightLeSample light_sample = sample_light_Le(xi_position, xi_direction, pc.num_lights);
	if (light_sample.pdf_joint <= 0.0) {
		return false;
	}
	vec2 canonical_uv = light_sample.identity.bary;
	const uint light_type = get_light_type(light_sample.flags);
	if (light_type == LIGHT_POINT || light_type == LIGHT_SPOT) {
		canonical_uv = xi_direction;
	} else if (light_type == LIGHT_DIRECTIONAL) {
		canonical_uv = xi_position.yz;
	}
	light_state.pos = light_sample.position;
	light_state.pdf_position_a = light_sample.pdf_position_a;
	light_state.dir = light_sample.wi;
	light_state.hash_idx = get_restir_hash_idx(light_sample.identity.light_idx, canonical_uv.x, canonical_uv.y);
	light_state.normal = light_sample.normal;
	light_state.pdf_direction_w = light_sample.pdf_direction_w;
	light_state.Le = light_sample.Le;
	light_state.light_flags = light_sample.flags;
	light_state.cos_from_light = light_sample.cos_from_light;
	light_state.area = 1.0 / light_sample.pdf_position_a;
	return true;
}

void main() {
	LightState light_state;
	bool generate_samples = true;
	if (vcm_generate_light_sample(light_state)) {
		if (should_resample.d == 0 && pc.do_spatiotemporal == 1) {
			temporal_reservoirs.d[light_state.hash_idx].selected_idx = pixel_idx;
		}
		light_states.d[pixel_idx] = light_state;
	}
}
