#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable

#include "../../../bda.glsl"
#include "restirgi_commons.h"
#include "../../../utils.glsl"

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
layout(binding = 0, rgba32f) uniform image2D image;
layout(binding = 1) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(push_constant) uniform _PushConstantRay { PCReSTIRGI pc; };
#include "../../../surface.glsl"

SCENE_BUFFER(restir_samples, ReservoirSample);
SCENE_BUFFER(color_storage, vec3);
SCENE_BUFFER(temporal_reservoir, Reservoir);
SCENE_BUFFER(spatial_reservoir, Reservoir);

uint offset(const uint pingpong) { return pingpong * pc.width * pc.height; }

void main() {
	ivec2 coords = ivec2(gl_GlobalInvocationID.x / pc.height, gl_GlobalInvocationID.x % pc.height);
	if (gl_GlobalInvocationID.x >= pc.width * pc.height) {
		return;
	}
	const uint pingpong = (pc.total_frame_num % 2);
	vec3 col = vec3(0);
	if (pc.enable_di == 1) {
		col += DEREF(color_storage)[gl_GlobalInvocationID.x];
	}
	uint idx = gl_GlobalInvocationID.x;
	DEREF(color_storage)[gl_GlobalInvocationID.x] = vec3(0);
	const Reservoir r = DEREF(spatial_reservoir)[offset(pingpong) + gl_GlobalInvocationID.x];
	if (r.W > 0 && surface_ref_valid(r.s.x_v_surface) && surface_ref_valid(r.s.x_s_surface)) {
		const ReservoirSample s = r.s;
		const SurfaceData x_v = load_surface(s.x_v_surface);
		const SurfaceData x_s = load_surface(s.x_s_surface);
		const vec3 wi = normalize(x_s.pos - x_v.pos);
		col += s.f * abs(dot(wi, x_v.n_s)) * s.L_o * r.W;
	}
	if (pc.enable_accumulation == 0 || pc.frame_num == 0) {
		imageStore(image, ivec2(coords), vec4(col, 1.f));
	} else {
		float w = 1. / float(pc.frame_num + 1);
		vec3 old_col = imageLoad(image, ivec2(coords)).xyz;
		imageStore(image, ivec2(coords), vec4(mix(old_col, col, w), 1.f));
	}
}
