#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

#include "../../../bda.glsl"
#include "restirgi_commons.h"
#include "../../../commons.glsl"
#include "../../../surface.glsl"
layout(location = 0) rayPayloadEXT SurfaceHitPayload payload;
layout(location = 1) rayPayloadEXT AnyHitPayload any_hit_payload;
layout(push_constant) uniform _PushConstantRay { PCReSTIRGI pc; };
const uint flags = gl_RayFlagsOpaqueEXT;
const float tmin = 0.001;
const float tmax = 10000.0;
#define RR_MIN_DEPTH 3
uint pixel_idx = (gl_LaunchIDEXT.x * gl_LaunchSizeEXT.y + gl_LaunchIDEXT.y);
uvec4 seed = init_rng(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy, pc.random_num);
SCENE_BUFFER(restir_samples, ReservoirSample);
SCENE_BUFFER(color_storage, vec3);
#include "../../pt_commons.glsl"

void main() {
    const vec2 pixel = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 in_uv = pixel / vec2(gl_LaunchSizeEXT.xy);
    vec2 d = in_uv * 2.0 - 1.0;
    vec4 origin = ubo.inv_view * vec4(0, 0, 0, 1);
    vec4 target = ubo.inv_projection * vec4(d.x, d.y, 1, 1);
    vec3 direction = vec3(sample_camera(d));
    vec3 col = vec3(0);
    SurfaceRef x_v_surface = invalid_surface_ref();
    SurfaceRef x_s_surface = invalid_surface_ref();
    float p_q = 0;
    vec3 L_o = vec3(0);
    vec3 x_f = vec3(0);
    uint bsdf_props = 0;
    vec4 area_int = (ubo.inv_projection * vec4(2. / gl_LaunchSizeEXT.x,
                                               2. / gl_LaunchSizeEXT.y, 0, 1));
    area_int /= (area_int.w);
    const float cam_area = abs(area_int.x * area_int.y);
    bool specular = false;
    vec3 throughput = vec3(1);
    vec3 t0 = vec3(1);
    for (int depth = 0;; depth++) {
        traceRayEXT(tlas, flags, 0xFF, 0, 0, 0, origin.xyz, tmin, direction,
                    tmax, 0);
        const bool found_isect = surface_ref_valid(payload.surface);
        if (depth >= pc.max_depth - 1) {
            break;
        }
        if (!found_isect) {
            const vec3 val = throughput * pc.sky_col;
            if(depth <= 1) {
                col += t0 * val;
            } else {
                L_o += t0 * val;
            }
         
            break;
        }

        const SurfaceData surface = load_surface(payload.surface);
        const Material hit_mat = load_material(surface.material_idx, surface.uv);
        if (depth == 0 || specular) {
            const vec3 val = throughput * hit_mat.emissive_factor;
            if (depth > 0) {
                L_o += val;
            } else {
                col += val;
            }
        }
        const vec3 wo = -direction;
        vec3 shading_nrm = surface.n_s;
        vec3 geometry_nrm = surface.n_g;
        const bool side = face_forward(shading_nrm, geometry_nrm, wo);
        const vec3 pos = surface.pos;
        if (depth == 1) {
            x_s_surface = payload.surface;
        }
        if ((hit_mat.bsdf_props & BSDF_FLAG_SPECULAR) == 0) {
			const vec3 val = throughput *
							 sample_direct_light(seed, hit_mat, surface.pos, side,
											 shading_nrm, geometry_nrm, wo, /*use_mis=*/false,
											 specular);
            if (depth > 0) {
                L_o += val;
            } else {
                col += val;
            }
        }
        // Sample direction & update throughput
        float pdf, cos_theta;
		const vec3 f = sample_bsdf(shading_nrm, geometry_nrm, wo, hit_mat, TRANSPORT_MODE_FROM_CAMERA,
								   side, direction, pdf, cos_theta, seed);

        if (pdf == 0) {
            break;
        }

        if (depth == 0) {
            x_v_surface = payload.surface;
            p_q = pdf;
            x_f = f;
            bsdf_props = hit_mat.bsdf_props;
        }

        if (depth > 0) {
            throughput *= f * abs(cos_theta) / pdf;
        } else {
            t0 = f * abs(cos_theta) / pdf;
        }
        specular = (hit_mat.bsdf_props & BSDF_FLAG_SPECULAR) != 0;
        origin.xyz = offset_ray(pos, geometry_nrm, direction);
        float rr_scale = 1.0;
        if (bsdf_has_property(hit_mat.bsdf_props, BSDF_FLAG_TRANSMISSION)) {
            rr_scale *= side ? 1. / hit_mat.ior : hit_mat.ior;
        }
        if (depth > RR_MIN_DEPTH) {
            float rr_prob = min(0.95f, luminance(throughput) * rr_scale);
            if (rr_prob < rand(seed))
                break;
            else
                throughput /= rr_prob;
        }
    }
    ivec2 coords = ivec2(0.5 * (1 + d) * vec2(pc.width, pc.height));
    uint coords_idx = coords.x * pc.height + coords.y;
    // Fill in the samples buffer
    DEREF(restir_samples)[pixel_idx].x_v_surface = x_v_surface;
    DEREF(restir_samples)[pixel_idx].x_s_surface = x_s_surface;
    DEREF(restir_samples)[pixel_idx].L_o = L_o;
    DEREF(restir_samples)[pixel_idx].p_q = p_q;
    DEREF(restir_samples)[pixel_idx].f = x_f;
    DEREF(restir_samples)[pixel_idx].bsdf_props = bsdf_props;
    DEREF(color_storage)[pixel_idx] += col;
}
