#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

#include "restirgi_commons.h"
#include "../../../commons.glsl"
layout(location = 0) rayPayloadEXT SurfaceHitPayload payload;
layout(location = 1) rayPayloadEXT AnyHitPayload any_hit_payload;
#include "restirgi_commons.glsl"
#define M_MAX 30

SCENE_BUFFER(restir_samples, ReservoirSample);
SCENE_BUFFER(restir_samples_old, ReservoirSample);
SCENE_BUFFER(temporal_reservoir, Reservoir);
SCENE_BUFFER(spatial_reservoir, Reservoir);

#define tr DEREF(temporal_reservoir)[offset(pingpong ^ 1) + pixel_idx]
void main() {
    const uint pingpong = (pc.total_frame_num % 2);
    const vec2 pixel = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const ReservoirSample s = DEREF(restir_samples)[pixel_idx];
    Reservoir r;
    if (!surface_ref_valid(s.x_v_surface) || !surface_ref_valid(s.x_s_surface)) {
        init_reservoir(r);
        tr.w_sum = r.w_sum;
        tr.W = r.W;
        tr.m = r.m;
        tr.s = r.s;
        DEREF(spatial_reservoir)[offset(pingpong ^ 1) + pixel_idx] = r;
        return;
    }
    const SurfaceData s_v = load_surface(s.x_v_surface);
    if (pc.do_spatiotemporal == 0) {
        init_reservoir(r);
    } else {
        vec4 prev_pos = ubo.prev_view * vec4(s_v.pos, 1);
        prev_pos /= prev_pos.z;
        prev_pos = -ubo.prev_projection * prev_pos;
        const vec2 prev_ndc = prev_pos.xy;
        ivec2 prev_coords = ivec2(0.5 * (1 + prev_ndc) * gl_LaunchSizeEXT.xy);
        bool reprojection_failed = true;
        uint prev_coords_idx;
        if (prev_coords.x >= 0 && prev_coords.x < gl_LaunchSizeEXT.x &&
            prev_coords.y >= 0 && prev_coords.y < gl_LaunchSizeEXT.y) {
            prev_coords_idx = prev_coords.x * pc.height + prev_coords.y;
            const ReservoirSample current_reprojected = DEREF(restir_samples)[prev_coords_idx];
            const ReservoirSample previous_current = DEREF(restir_samples_old)[pixel_idx];
            if (surface_ref_valid(current_reprojected.x_v_surface) &&
                surface_ref_valid(previous_current.x_v_surface)) {
                const SurfaceData current_reprojected_v = load_surface(current_reprojected.x_v_surface);
                const SurfaceData previous_current_v = load_surface(previous_current.x_v_surface);
                if (similar(current_reprojected_v, previous_current_v)) {
                    reprojection_failed = false;
                }
            }
        }
        if (!reprojection_failed) {
            r = DEREF(temporal_reservoir)[offset(pingpong) + prev_coords_idx];
        } else {
            // Reprojection failed, reset both reservoirs
            // Temporal
            init_reservoir(r);
            // Spatial
            DEREF(spatial_reservoir)[offset(pingpong ^ 1) + pixel_idx] = r;
        }
    }
    Reservoir r_new;
    r_new.w_sum = 0;
    r_new.W = 0;
    r_new.m = 0;
    const float phat = p_hat(s.L_o);
    const float w = phat / s.p_q;
    update_reservoir(r_new, s, w);
    r_new.W = phat == 0 ? 0 : r_new.w_sum / (r_new.m * phat);

    Reservoir r_t;
    r_t.w_sum = 0;
    r_t.W = 0;
    r_t.m = 0;
    // Combine new
    update_reservoir(r_t, r_new.s, r_new.m * r_new.W * phat);
    // Combine previous
    update_reservoir(r_t, r.s, r.m * r.W * p_hat(r.s.L_o));
    uint mval = r.m;
    const float new_phat = p_hat(r_t.s.L_o);
    if (new_phat > 0) {
        mval++;
    }
    r_t.m = min(r.m + 1, M_MAX);
    r_t.W = new_phat * mval == 0 ? 0 : r_t.w_sum / (mval * new_phat);

    tr.w_sum = r_t.w_sum;
    tr.W = r_t.W;
    tr.m = r_t.m;
    tr.s = r_t.s;
}
