#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
#include "ir_commons.h"
layout(binding = 0) buffer HashEntryBuffer { HashEntry hash_entries[]; };
layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };

void main() {
    if(gl_GlobalInvocationID.x >= pc.max_hash_table_size) {
        return;
    }
    GBuffer gbuffer_out;
    gbuffer_out.primitive_instance_id = uvec2(-1);
    hash_entries[gl_GlobalInvocationID.x].representative_point = gbuffer_out;
}