#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

#include "../../bda.glsl"
#include "ir_commons.h"

layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(binding = 1, rgba32f) uniform image2D image;
layout(binding = 2) uniform SceneUBOBuffer { SceneUBO ubo; };
layout(binding = 3) uniform sampler2D scene_textures[];
#include "../../scene_buffers.glsl"

SCENE_BUFFER(surfel_pool, Surfel);
SCENE_BUFFER(grid_cell_indices, uint);
SCENE_BUFFER(grid_cell_counts, uint);
SCENE_BUFFER(direct_lighting, vec3);

#include "../../utils.glsl"
#include "../../bsdf_commons.glsl"
#include "ir_commons.glsl"
layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };

SCENE_BUFFER(g_buffer, SurfaceRef);
#include "hash.glsl"
#include "grid.glsl"

layout(local_size_x = SURFELIZE_PASS_TILE_SIZE_XY, local_size_y = SURFELIZE_PASS_TILE_SIZE_XY, local_size_z = 1) in;

void store_output(const ivec2 coords, vec3 col) {
	if (pc.enable_accumulation == 1 && pc.frame_num > 0) {
		const float weight = 1.0 / float(pc.frame_num + 1);
		col = mix(imageLoad(image, coords).xyz, col, weight);
	}
	imageStore(image, coords, vec4(col, 1));
}

void main() {
	ivec2 coords = ivec2(gl_GlobalInvocationID.xy);

	uint pixel_idx = coords.x * pc.height + coords.y;
	if (coords.x >= pc.width || coords.y >= pc.height) {
		return;
	}

	vec3 col = pc.direct_lighting == 1 ? DEREF(direct_lighting)[pixel_idx] : vec3(0);
	SurfaceRef gbuffer = DEREF(g_buffer)[pixel_idx];

	if (!surface_ref_valid(gbuffer)) {
		store_output(coords, col);
		return;
	}

	SurfaceData hit_data = load_surface(gbuffer);

	vec3 pixel_world_pos = hit_data.pos;
	vec4 cam_pos = ubo.inv_view * vec4(0, 0, 0, 1);
	vec3 offset = pixel_world_pos - cam_pos.xyz;
	uvec4 grid_val = map_grid_axis(offset);
	uint linear_idx = linearize_grid(grid_val);
	uint surfel_count = DEREF(grid_cell_counts)[linear_idx + 1] - DEREF(grid_cell_counts)[linear_idx];
	uint surfel_offset = DEREF(grid_cell_counts)[linear_idx];

	vec3 irradiance_sum = vec3(0);
	float weight_sum = 0;

	uvec4 base = map_grid_axis(offset);
	for (uint gid = 0; gid < surfel_count; gid++) {
		uint sid = DEREF(grid_cell_indices)[gid + surfel_offset];
		Surfel surfel = DEREF(surfel_pool)[sid];
		if(surfel.radius <= 0.0) continue;


		SurfaceData surfel_hit_data = load_surface(surfel.gbuffer);

		vec3 from_surfel_center = hit_data.pos - surfel_hit_data.pos;
		float dist = length(from_surfel_center);

		float n_dot = dot(hit_data.n_s, surfel_hit_data.n_s);
		if (n_dot < 0.3) {
			continue;
		}

		float dist_normal = dot(from_surfel_center, surfel_hit_data.n_s);
		float dist_tangent = sqrt(max(0.0, dist * dist - dist_normal * dist_normal));

		// Penalize normal distance
		float dist_aniso = sqrt(dist_tangent * dist_tangent + 4.0 * dist_normal * dist_normal);

		float ratio = dist_aniso / surfel.radius;

		float weight_pos = pow(max(5.0 - ratio, 0.0), 4.0) * (4.0 * ratio + 1.0);

		float weight_normal = pow(max(dot(hit_data.n_s, surfel_hit_data.n_s), 0.0), 4.0);

		float weight = weight_pos * weight_normal;
		weight_sum += weight;
		irradiance_sum += weight * surfel.irradiance;
	}

	vec3 irradiance = weight_sum > 0 ? irradiance_sum / weight_sum : vec3(0);

	Material material = load_material(hit_data.material_idx, hit_data.uv);
	vec3 wo = normalize(cam_pos.xyz - pixel_world_pos);
	vec3 n_s = hit_data.n_s;
	vec3 n_g = hit_data.n_g;
	bool side = face_forward(n_s, n_g, wo);
	vec3 wi = n_s;
	vec3 f = eval_bsdf(n_s, n_g, wo, material, TRANSPORT_MODE_FROM_CAMERA, side, wi);

	vec3 indirect_radiance = f * irradiance;
	col += indirect_radiance;
	store_output(coords, col);
}
