#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
#extension GL_KHR_shader_subgroup_arithmetic : enable

#include "ir_commons.h"
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer InstanceInfo { PrimInfo d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer Materials { Material m[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer Indices { uint i[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer CompactVertices { Vertex d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer SurfelPool { Surfel d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer SpawnCount { uint d; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer GridCellCounts { uint d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer GridCellIndices { uint d[]; };

Indices indices = Indices(scene_desc.index_addr);
Materials materials = Materials(scene_desc.material_addr);
InstanceInfo prim_infos = InstanceInfo(scene_desc.prim_info_addr);
CompactVertices compact_vertices = CompactVertices(scene_desc.compact_vertices_addr);
SurfelPool surfel_pool = SurfelPool(scene_desc.surfel_pool_addr);
SpawnCount spawn_count = SpawnCount(scene_desc.surfel_spawn_count_addr);
GridCellIndices grid_cell_indices = GridCellIndices(scene_desc.grid_cell_indices_addr);
GridCellCounts grid_cell_counts = GridCellCounts(scene_desc.grid_cell_counts_addr);

#include "ir_commons.glsl"

layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };
layout(binding = 1, rgba32f) uniform image2D image;
layout(binding = 2) uniform SceneUBOBuffer { SceneUBO ubo; };
layout(binding = 3) uniform sampler2D scene_textures[];
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer InGBuffer { GBuffer d[]; };
InGBuffer gbuffers = InGBuffer(scene_desc.g_buffer_addr);

#include "../../bsdf_commons.glsl"

#include "hash.glsl"
#include "grid.glsl"
#include "surfel_commons.glsl"

vec3 debug_col(uint num) {
	const float INV_11 = 1.0 / 2047.0;
	const float INV_10 = 1.0 / 1023.0;
	return vec3((float(num & 0x7FFu)) * INV_11, (float((num >> 11) & 0x7FFu)) * INV_11,
				(float((num >> 22) & 0x3FFu)) * INV_10);
}

vec3 uvec3_to_random_color(uvec3 value) { return debug_col(xxhash32(value)); }
vec3 uint_to_random_color(uint value) { return debug_col(xxhash32(value)); }

layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
void main() {
	ivec2 coords = ivec2(gl_GlobalInvocationID.x / pc.height, gl_GlobalInvocationID.x % pc.height);
	if (coords.x >= pc.width || coords.y >= pc.height) {
		return;
	}
	GBuffer gbuffer = gbuffers.d[gl_GlobalInvocationID.x];

	if (!gbuffer_valid(gbuffer)) {
		imageStore(image, coords, vec4(vec3(0), 1.f));
		return;
	}
	vec3 col = vec3(0);
	imageStore(image, coords, vec4(col, 1.f));
}
