#version 460
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_debug_printf : enable

#include "ir_commons.h"
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(binding = 1, rgba32f) uniform image2D image;
layout(binding = 2) uniform SceneUBOBuffer { SceneUBO ubo; };
layout(binding = 3) uniform sampler2D scene_textures[];
layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer InstanceInfo { PrimInfo d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer Indices { uint i[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer CompactVertices { Vertex d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer SurfelPool { Surfel d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer GridCellCounts { uint d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer GridCellIndices { uint d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer Materials { Material m[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer InGBuffer { GBuffer d[]; };

Indices indices = Indices(scene_desc.index_addr);
InstanceInfo prim_infos = InstanceInfo(scene_desc.prim_info_addr);
CompactVertices compact_vertices = CompactVertices(scene_desc.compact_vertices_addr);
SurfelPool surfel_pool = SurfelPool(scene_desc.surfel_pool_addr);
GridCellIndices grid_cell_indices = GridCellIndices(scene_desc.grid_cell_indices_addr);
GridCellCounts grid_cell_counts = GridCellCounts(scene_desc.grid_cell_counts_addr);
Materials materials = Materials(scene_desc.material_addr);
InGBuffer gbuffers = InGBuffer(scene_desc.g_buffer_addr);

#include "../../bsdf_commons.glsl"
#include "ir_commons.glsl"
#include "hash.glsl"
#define PRINT_GRID
#include "grid.glsl"

vec3 debug_col(uint num) {
	const float INV_11 = 1.0 / 2047.0;
	const float INV_10 = 1.0 / 1023.0;
	return vec3((float(num & 0x7FFu)) * INV_11, (float((num >> 11) & 0x7FFu)) * INV_11,
				(float((num >> 22) & 0x3FFu)) * INV_10);
}


vec3 uvec3_to_random_color(uvec3 value) { return debug_col(xxhash32(value)); }
vec3 uint_to_random_color(uint value) { return debug_col(xxhash32(value)); }


layout(local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;
void main() {
	ivec2 coords = ivec2(gl_GlobalInvocationID.x / pc.height, gl_GlobalInvocationID.x % pc.height);
	if (coords.x >= pc.width || coords.y >= pc.height) {
		return;
	}
	GBuffer gbuffer = gbuffers.d[gl_GlobalInvocationID.x];

	if (!gbuffer_valid(gbuffer)) {
		imageStore(image, coords, vec4(vec3(0), 1.f));
		return;
	}

	HitData hit_data = get_hitdata(gbuffer);

	if (pc.debug_view == IRCACHE_DEBUG_VIEW_GBUFFER_NORMALS) {
		imageStore(image, coords, vec4(hit_data.n_s * 0.5 + 0.5, 1.f));
		return;
	} else if (pc.debug_view == IRCACHE_DEBUG_VIEW_GBUFFER_ALBEDO) {
		Material material = load_material(hit_data.material_idx, hit_data.uv);
		imageStore(image, coords, vec4(material.albedo, 1.f));
		return;
	}

	vec3 pixel_world_pos = hit_data.pos;
	vec4 cam_pos = ubo.inv_view * vec4(0, 0, 0, 1);
	vec3 cam_relative_pos = pixel_world_pos - cam_pos.xyz;

	vec3 grid_pos_begin;
	vec3 grid_pos_end;
	uvec4 grid_val = map_grid_axis(cam_relative_pos, grid_pos_begin, grid_pos_end);
	uint linear_idx = linearize_grid(grid_val);
	uint surfel_count = grid_cell_counts.d[linear_idx + 1] - grid_cell_counts.d[linear_idx];
	uint surfel_offset = grid_cell_counts.d[linear_idx];
	bool is_max_count_cell = pc.max_surfels_in_a_grid_cell > 0 && surfel_count == pc.max_surfels_in_a_grid_cell;

	uvec4 res = map_grid_axis(cam_relative_pos);
	vec3 col = uvec3_to_random_color(res.yzw) * 0.5;
	vec3 grid_base_color = uint_to_random_color(xxhash32(res.x));
	col *= grid_base_color;

	vec3 pos_abs = abs(cam_relative_pos);
	float max_abs_dir = max(pos_abs.x, pos_abs.y);
	max_abs_dir = max(max_abs_dir, pos_abs.z);
	if (abs(max_abs_dir - pos_abs.x) < 1e-3 && abs(max_abs_dir - pos_abs.z) < 1e-3) {
		col = vec3(100, 0, 0);
	}
	vec3 grid_bbox = grid_pos_end - grid_pos_begin;
	vec3 cell_uv = (cam_relative_pos - grid_pos_begin) / (grid_pos_end - grid_pos_begin);

	vec2 normalized_uvs = compute_normalized_uvs(cell_uv, grid_val.x);
	if (ubo.debug_click == 1 && ivec2(coords.xy) == ubo.clicked_pos) {
		debugPrintfEXT("Grid at mouse %v3u , region %d\n", grid_val.yzw, grid_val.x);
	}

	if (pc.debug_view == IRCACHE_DEBUG_VIEW_TRAPEZOIDAL_GRID) {
		if (is_max_count_cell) {
			col = vec3(100, 0, 0);
		}
		imageStore(image, coords, vec4(col, 1.f));
		return;
	}

	float best_weight = 0.0;
	uint best_sid = 0xFFFFFFFF;
	uint overlapping_surfel_cnt = 0;

	int idx = 0;
	for (uint gid = 0; gid < surfel_count; gid++) {
		uint sid = grid_cell_indices.d[gid + surfel_offset];
		Surfel surfel = surfel_pool.d[sid];
		HitData surfel_hit_data = get_hitdata(surfel.gbuffer);

		vec3 diff = hit_data.pos - surfel_hit_data.pos;
		float dist = length(diff);
		if (dist > surfel.radius) {
			continue;
		}

		float n_dot = dot(hit_data.n_s, surfel_hit_data.n_s);
		if (n_dot < 0.3) {
			continue;
		}

		float dist_normal = dot(diff, surfel_hit_data.n_s);
		float dist_tangent = sqrt(max(0.0, dist * dist - dist_normal * dist_normal));

		// Penalize normal distance
		float dist_aniso = sqrt(dist_tangent * dist_tangent + 4.0 * dist_normal * dist_normal);

		if (dist_aniso > surfel.radius) {
			continue;
		}


		float weight = (1.0 - dist_aniso / surfel.radius) * n_dot;

		if (ubo.debug_click == 1 && ivec2(coords.xy) == ubo.clicked_pos) { 
			// debugPrintfEXT("(%d)Surfel %d, dist %f, n_dot %f, weight %f\n", idx, sid, dist_aniso, n_dot, weight);
		}

		if (weight > best_weight) {
			overlapping_surfel_cnt++;
			best_weight = weight;
			best_sid = sid;
		}
		idx++;
	}

	if (best_sid != 0xFFFFFFFF) {
		vec3 surfel_color = uint_to_random_color(best_sid);
		if (overlapping_surfel_cnt > 1) {
			col = vec3(100, 0, 100);
		} else {
			col = is_max_count_cell ? vec3(100, 0, 0) : surfel_color;
		}

		Surfel surfel = surfel_pool.d[best_sid];
		HitData surfel_hit_data = get_hitdata(surfel.gbuffer);
		if (ubo.debug_click == 1 && ivec2(coords.xy) == ubo.clicked_pos) {
			uvec4 neighbors[MAX_NEIGHBOR_PLUS_ITSELF_COUNT];
			uint neighbor_count;
			collect_neighbors(surfel_hit_data.pos, surfel.radius, cam_pos.xyz, neighbors, neighbor_count);
			debugPrintfEXT("Selected id %d\n", best_sid);
		}
	}

	imageStore(image, coords, vec4(col, 1.f));
}
