#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

#include "../../bda.glsl"
#include "ir_commons.h"
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };

layout(push_constant) uniform _PushConstantPrefixSum { PCPrefixSum pc; };


SCENE_BUFFER(grid_cell_counts, uint);
SCENE_BUFFER(grid_prefix_sum_scratch, uint);

layout(local_size_x = SCAN_WG_SIZE, local_size_y = 1, local_size_z = 1) in;
void main() {
	uint tid = gl_GlobalInvocationID.x;

	uint block_sum =
		gl_WorkGroupID.x == 0 ? 0 : DEREF(grid_prefix_sum_scratch)[pc.out_offset + gl_WorkGroupID.x - 1];

	if (tid < pc.num_elems) {
		if (pc.scan_sums == 0) {
			DEREF(grid_cell_counts)[tid] += block_sum;
		} else {
			DEREF(grid_prefix_sum_scratch)[pc.block_sum_offset + tid] += block_sum;
		}
	}
}
