#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

#include "../../bda.glsl"
#include "ir_commons.h"
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(binding = 1) uniform SceneUBOBuffer { SceneUBO ubo; };
#include "../../scene_buffers.glsl"

layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };


SCENE_BUFFER(grid_cell_indices, uint);
SCENE_BUFFER(grid_cell_counts, uint);
SCENE_BUFFER(surfel_pool, Surfel);

#include "ir_commons.glsl"
#include "grid.glsl"

layout(local_size_x = ALLOCATE_PASS_WG_SIZE, local_size_y = 1, local_size_z = 1) in;
void main() {
	uint surfel_idx = gl_GlobalInvocationID.x;
	if (surfel_idx >= MAX_SURFEL_COUNT) {
		return;
	}
	// TODO: Check surfel status?
	Surfel surfel = DEREF(surfel_pool)[surfel_idx];

	if (surfel.radius <= 0.0f) {
		return;
	}

	vec4 cam_pos = ubo.inv_view * vec4(0, 0, 0, 1);
	SurfaceData surfel_hit_data = load_surface(surfel.gbuffer);
	// Offset around camera
	vec3 c = surfel_hit_data.pos - cam_pos.xyz;
	float r = surfel.radius;

#if GRID_LOOKUP_MODE == GRID_LOOKUP_BBOX
	vec3 corners[8] = vec3[8](c + vec3(-r, -r, -r), c + vec3(-r, -r, +r), c + vec3(-r, +r, -r), c + vec3(-r, +r, +r),
							  c + vec3(+r, -r, -r), c + vec3(+r, -r, +r), c + vec3(+r, +r, -r), c + vec3(+r, +r, +r));

	uvec4 results[8];
	for (int i = 0; i < 8; i++) {
		results[i] = map_grid_axis(corners[i]);
	}

	uint linear_cells[8];
	uint unique_cnt = 0;

	for (uint i = 0; i < 8; i++) {
		uint linear_idx = linearize_grid(results[i]);

		bool is_duplicate = false;
		for (uint j = 0; j < unique_cnt; j++) {
			if (linear_idx == linear_cells[j]) {
				is_duplicate = true;
				break;
			}
		}
		if (!is_duplicate) {
			linear_cells[unique_cnt] = linear_idx;
			unique_cnt++;
		}
	}

	// This is fine as long as a surfel is smaller than the grid cell size
	for (uint i = 0; i < unique_cnt; i++) {
		uint cell_end = atomicAdd(DEREF(grid_cell_counts)[linear_cells[i]], -1);
		uint idx = cell_end - 1;
#if DEBUG_GRID_INVARIANTS
		if (cell_end == 0 || idx >= (GRID_AVG_SURFELS_PER_CELL * MAX_SURFEL_COUNT)) {
			debugPrintfEXT("Invalid grid cell offset %u\n", idx);
			continue;
		}
#endif
		DEREF(grid_cell_indices)[idx] = surfel_idx;
	}
#else
	uvec4 neighbors[MAX_NEIGHBOR_PLUS_ITSELF_COUNT];
	uint neighbor_count;
	collect_neighbors(surfel_hit_data.pos, r, cam_pos.xyz, neighbors, neighbor_count);

	for (uint i = 0; i < neighbor_count; i++) {
		uint linear_idx = linearize_grid(neighbors[i]);
		uint cell_end = atomicAdd(DEREF(grid_cell_counts)[linear_idx], -1);
		uint idx = cell_end - 1;
#if DEBUG_GRID_INVARIANTS
		if (cell_end == 0 || idx >= (GRID_AVG_SURFELS_PER_CELL * MAX_SURFEL_COUNT)) {
			debugPrintfEXT("Invalid grid cell offset %u\n", idx);
			continue;
		}
#endif
		DEREF(grid_cell_indices)[idx] = surfel_idx;
	}
#endif
}
