#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

#include "ir_commons.h"
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(binding = 1) uniform SceneUBOBuffer { SceneUBO ubo; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer InstanceInfo { PrimInfo d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer Indices { uint i[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer CompactVertices { Vertex d[]; };

Indices indices = Indices(scene_desc.index_addr);
InstanceInfo prim_infos = InstanceInfo(scene_desc.prim_info_addr);
CompactVertices compact_vertices = CompactVertices(scene_desc.compact_vertices_addr);

layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };

layout(buffer_reference, scalar, buffer_reference_align = 4) buffer GridCellIndices { uint d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer GridCellCounts { uint d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer SurfelPool { Surfel d[]; };

GridCellIndices grid_cell_indices = GridCellIndices(scene_desc.grid_cell_indices_addr);
GridCellCounts grid_cell_counts = GridCellCounts(scene_desc.grid_cell_counts_addr);
SurfelPool surfel_pool = SurfelPool(scene_desc.surfel_pool_addr);

#include "ir_commons.glsl"
#include "grid.glsl"

layout(local_size_x = ALLOCATE_PASS_WG_SIZE, local_size_y = 1, local_size_z = 1) in;
void main() {
	uint surfel_idx = gl_GlobalInvocationID.x;
	if (surfel_idx >= MAX_SURFEL_COUNT) {
		return;
	}
	// TODO: Check surfel status?
	Surfel surfel = surfel_pool.d[surfel_idx];

	if (surfel.radius <= 0.0f) {
		return;
	}

	vec4 cam_pos = ubo.inv_view * vec4(0, 0, 0, 1);
	HitData surfel_hit_data = get_hitdata(surfel.gbuffer);
	// Offset around camera
	vec3 c = surfel_hit_data.pos - cam_pos.xyz;
	float r = surfel.radius;

#if GRID_LOOKUP_MODE == GRID_LOOKUP_BBOX
	vec3 corners[8] = vec3[8](c + vec3(-r, -r, -r), c + vec3(-r, -r, +r), c + vec3(-r, +r, -r), c + vec3(-r, +r, +r),
							  c + vec3(+r, -r, -r), c + vec3(+r, -r, +r), c + vec3(+r, +r, -r), c + vec3(+r, +r, +r));

	uvec4 results[8];
	for (int i = 0; i < 8; i++) {
		results[i] = map_grid_axis(corners[i]);
	}

	uint linear_cells[8];
	uint unique_cnt = 0;

	for (uint i = 0; i < 8; i++) {
		uint linear_idx = linearize_grid(results[i]);

		bool is_duplicate = false;
		for (uint j = 0; j < unique_cnt; j++) {
			if (linear_idx == linear_cells[j]) {
				is_duplicate = true;
				break;
			}
		}
		if (!is_duplicate) {
			linear_cells[unique_cnt] = linear_idx;
			unique_cnt++;
		}
	}

	// This is fine as long as a surfel is smaller than the grid cell size
	for (uint i = 0; i < unique_cnt; i++) {
		uint cell_end = atomicAdd(grid_cell_counts.d[linear_cells[i]], -1);
		uint idx = cell_end - 1;
#if DEBUG_GRID_INVARIANTS
		if (cell_end == 0 || idx >= (GRID_AVG_SURFELS_PER_CELL * MAX_SURFEL_COUNT)) {
			debugPrintfEXT("Invalid grid cell offset %u\n", idx);
			continue;
		}
#endif
		grid_cell_indices.d[idx] = surfel_idx;
	}
#else
	uvec4 neighbors[4];
	uint neighbor_count;
	collect_neighbors(surfel_hit_data.pos, r, cam_pos.xyz, neighbors, neighbor_count);

	for (uint i = 0; i < neighbor_count; i++) {
		uint linear_idx = linearize_grid(neighbors[i]);
		uint cell_end = atomicAdd(grid_cell_counts.d[linear_idx], -1);
		uint idx = cell_end - 1;
#if DEBUG_GRID_INVARIANTS
		if (cell_end == 0 || idx >= (GRID_AVG_SURFELS_PER_CELL * MAX_SURFEL_COUNT)) {
			debugPrintfEXT("Invalid grid cell offset %u\n", idx);
			continue;
		}
#endif
		grid_cell_indices.d[idx] = surfel_idx;
	}
#endif
}
