#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_KHR_shader_subgroup_arithmetic : enable

#include "../../bda.glsl"
#include "ir_commons.h"
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };

layout(push_constant) uniform _PushConstantPrefixSum { PCPrefixSum pc; };


SCENE_BUFFER(grid_cell_counts, uint);
SCENE_BUFFER(grid_prefix_sum_scratch, uint);

shared uint subgroup_data[SUBGROUP_SIZE];

layout(local_size_x = SCAN_WG_SIZE, local_size_y = 1, local_size_z = 1) in;
void main() {
	uint tid = gl_GlobalInvocationID.x;

	uint count;

	if (tid < pc.num_elems) {
		count = pc.scan_sums == 0 ? DEREF(grid_cell_counts)[tid] : DEREF(grid_prefix_sum_scratch)[pc.block_sum_offset + tid];
	} else {
		count = 0;
	}

	uint sum = subgroupInclusiveAdd(count);

	if (gl_SubgroupInvocationID == gl_SubgroupSize - 1) {
		subgroup_data[gl_SubgroupID] = sum;
	}
	barrier();

	uint sum_wgs = 0;
	if (gl_SubgroupID == 0) {
		uint sum_subgroup = gl_SubgroupInvocationID < gl_NumSubgroups ? subgroup_data[gl_SubgroupInvocationID] : 0;
		sum_wgs = subgroupExclusiveAdd(sum_subgroup);
	}
	barrier();

	if (gl_SubgroupID == 0 && gl_SubgroupInvocationID < gl_NumSubgroups) {
		subgroup_data[gl_SubgroupInvocationID] = sum_wgs;
	}
	barrier();
	sum += subgroup_data[gl_SubgroupID];

	if (tid < pc.num_elems) {
		if (pc.scan_sums == 0) {
			DEREF(grid_cell_counts)[tid] = sum;
		} else {
			DEREF(grid_prefix_sum_scratch)[pc.block_sum_offset + tid] = sum;
		}
#ifndef DISABLE_SUM_WRITES
		if ((gl_LocalInvocationID.x == SCAN_WG_SIZE - 1) || (tid == pc.num_elems - 1)) {
			DEREF(grid_prefix_sum_scratch)[pc.out_offset + gl_WorkGroupID.x] = sum;
		}
#endif	// DISABLE_SUM_WRITES
	}
}
