#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

#include "../../commons.glsl"
#include "ir_commons.h"
const uint flags = gl_RayFlagsOpaqueEXT;
const float tmin = 0.001;
const float tmax = 10000.0;
uint pixel_idx = (gl_LaunchIDEXT.x * gl_LaunchSizeEXT.y + gl_LaunchIDEXT.y);
layout(location = 0) rayPayloadEXT IRCacheHitPayload payload;
layout(location = 1) rayPayloadEXT AnyHitPayload any_hit_payload;
layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer OutGBuffer { GBuffer d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer CurrentFrameLighting { vec3 d[]; };

#include "ir_commons.glsl"
#include "direct_lighting.glsl"

OutGBuffer gbuffers = OutGBuffer(scene_desc.g_buffer_addr);
CurrentFrameLighting current_frame_lighting = CurrentFrameLighting(scene_desc.direct_lighting_addr);

void store_direct_lighting(const ivec2 pixel, const vec3 radiance) {
	current_frame_lighting.d[pixel_idx] = radiance;
	if (pc.enable_accumulation == 0) {
		imageStore(image, pixel, vec4(radiance, 1));
	}
}

void main() {
	const ivec2 pixel = ivec2(gl_LaunchIDEXT.xy);
	const vec2 in_uv = (pixel + vec2(0.5)) / vec2(gl_LaunchSizeEXT.xy);
	const vec2 ndc = in_uv * 2.0 - 1.0;
	vec3 origin = ubo.view_pos.xyz;
	vec3 direction = vec3(sample_camera(ndc));
	direction = normalize(direction);
	uvec4 sampling_seed = init_rng(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy, pc.sampling_seed);
	vec3 direct_lighting = vec3(0);
	GBuffer gbuffer_out;
	gbuffer_out.barycentrics = vec2(0);
	gbuffer_out.primitive_instance_id = uvec2(-1);

	traceRayEXT(tlas, flags, 0x1, 0, 0, 0, origin, tmin, direction, tmax, 0);
	const bool found_isect = payload.instance_idx != -1;
	if (!found_isect) {
		gbuffers.d[pixel_idx] = gbuffer_out;
		if (pc.direct_lighting == 1) {
#ifdef ENABLE_ATMOSPHERE
			direct_lighting = shade_atmosphere(pc.dir_light_idx, pc.sky_col, origin, direction, tmax);
#else
			direct_lighting = pc.sky_col;
#endif	// ENABLE_ATMOSPHERE
		}
		store_direct_lighting(pixel, direct_lighting);
		return;
	}
	gbuffer_out.barycentrics = payload.attribs;
	gbuffer_out.primitive_instance_id = uvec2(payload.triangle_idx, payload.instance_idx);
	gbuffers.d[pixel_idx] = gbuffer_out;

	if (pc.direct_lighting == 1) {
		HitData hit_data = get_hitdata(gbuffer_out);
		vec3 wo = -direction;
		Material material = load_material(hit_data.material_idx, hit_data.uv);
		vec3 n_s = hit_data.n_s;
		vec3 n_g = hit_data.n_g;
		bool side = face_forward(n_s, n_g, wo);

		direct_lighting += material.emissive_factor;
		if (!is_specular(material)) {
			direct_lighting += sample_direct_light(sampling_seed, hit_data.pos, n_s, wo, material, side);
		}
	}
	store_direct_lighting(pixel, direct_lighting);
}
