#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_ballot : enable

#include "../../bda.glsl"
#include "ir_commons.h"
#include "../../random.glsl"
layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(binding = 1) uniform SceneUBOBuffer { SceneUBO ubo; };
#include "../../scene_buffers.glsl"

SCENE_BUFFER(grid_cell_indices, uint);
SCENE_BUFFER(grid_cell_counts, uint);

#include "ir_commons.glsl"
#include "grid.glsl"
#include "surfel_commons.glsl"


SCENE_BUFFER(g_buffer, SurfaceRef);
SCENE_BUFFER(surfel_spawn_list, uint);
SCENE_BUFFER_SCALAR(surfel_spawn_count, uint);
SCENE_BUFFER(surfel_pool, Surfel);

#define TILE_COVERAGE_MAX 1e6
#define TILE_PERIOD 3

// Process SURFELIZE_PASS_TILE_SIZE_XY * SURFELIZE_PASS_TILE_SIZE_XY tiles
// 1 threadgroup processes each pixels in a tile (1 thread = 1 pixel)
// Coverage is selected using warp intrinsics, per workgroup (tile)

// For warp size of 32 and tile size of 16, we have 256 / 32 = 8 subgroups
#define NUM_ACTIVE_SUBGROUPS (SURFELIZE_PASS_TILE_SIZE_XY * SURFELIZE_PASS_TILE_SIZE_XY / SUBGROUP_SIZE)
shared uint winner_pixels[NUM_ACTIVE_SUBGROUPS];
shared float winner_coverages[NUM_ACTIVE_SUBGROUPS];

layout(local_size_x = SURFELIZE_PASS_TILE_SIZE_XY, local_size_y = SURFELIZE_PASS_TILE_SIZE_XY, local_size_z = 1) in;

void main() {
	uvec2 pixel_coords = gl_GlobalInvocationID.xy;
	uint pixel_idx = (pixel_coords.x * pc.height + pixel_coords.y);

	uvec2 tile_coords = gl_WorkGroupID.xy;
	uint phase_x = pc.total_frame_num % TILE_PERIOD;
	uint phase_y = (pc.total_frame_num / TILE_PERIOD) % TILE_PERIOD;

	if ((tile_coords.x % TILE_PERIOD) != phase_x || (tile_coords.y % TILE_PERIOD) != phase_y) {
		return;
	}

	float coverage = TILE_COVERAGE_MAX;
	if (pixel_coords.x < pc.width && pixel_coords.y < pc.height) {
		SurfaceRef gbuffer = DEREF(g_buffer)[pixel_idx];
		if (surface_ref_valid(gbuffer)) {
			SurfaceData hit_data = load_surface(gbuffer);

			coverage = 0.0;
			vec4 cam_pos = ubo.inv_view * vec4(0, 0, 0, 1);
			vec3 offset = hit_data.pos - cam_pos.xyz;
			uvec4 grid_val = map_grid_axis(offset);
			uint linear_idx = linearize_grid(grid_val);
			uint surfel_offset = DEREF(grid_cell_counts)[linear_idx];
			uint surfel_count = DEREF(grid_cell_counts)[linear_idx + 1] - surfel_offset;
			float would_be_radius = surfel_radius_for_position(hit_data.pos);

			for (uint gid = 0; gid < surfel_count; gid++) {
				uint sid = DEREF(grid_cell_indices)[gid + surfel_offset];
				Surfel surfel = DEREF(surfel_pool)[sid];
				if (surfel.radius <= 0.0) continue;
				SurfaceData surfel_hit_data = load_surface(surfel.gbuffer);
				vec3 pos_to_surfel = hit_data.pos - surfel_hit_data.pos;
				float dist_sqr = dot(pos_to_surfel, pos_to_surfel);
				float dist_normal = dot(pos_to_surfel, surfel_hit_data.n_s);
				float dist_tangent = sqrt(max(0.0, dist_sqr - dist_normal * dist_normal));
				float n_dot = dot(hit_data.n_s, surfel_hit_data.n_s);

				if (n_dot < 0.3 || dist_tangent > (surfel.radius + would_be_radius)) {
					continue;
				}
				float weight = (1.0 - dist_tangent / (surfel.radius + would_be_radius)) * n_dot;
				coverage += weight;
			}
		}
	}
	uvec4 seed = init_rng(pixel_coords, uvec2(pc.width, pc.height), pc.total_frame_num);
	float jitter = rand(seed) * 1e-8;
	coverage += jitter;
	// Get the minimum coverage across the subgroup
	float min_coverage = subgroupMin(coverage);

	bool i_am_min = coverage == min_coverage;
	// Tie break
	uvec4 ballot = subgroupBallot(i_am_min);
	// Get the lowest subgroup idx (arbitrary)
	uint winner = subgroupBallotFindLSB(ballot);

	if (gl_SubgroupInvocationID == winner && i_am_min) {
		winner_pixels[gl_SubgroupID] = pixel_idx;
		winner_coverages[gl_SubgroupID] = coverage;
	}
	barrier();
	// Reduce between subgroups
	if (gl_SubgroupID == 0) {
		float their_coverage = gl_SubgroupInvocationID < NUM_ACTIVE_SUBGROUPS
								   ? winner_coverages[gl_SubgroupInvocationID]
								   : TILE_COVERAGE_MAX;
		float min_tile_coverage = subgroupMin(their_coverage);
		bool i_am_tile_min = min_tile_coverage == their_coverage;
		uvec4 ballot = subgroupBallot(i_am_tile_min);
		uint tile_winner = subgroupBallotFindLSB(ballot);

		if (gl_SubgroupInvocationID == tile_winner && min_tile_coverage < TILE_COVERAGE_MAX) {
			// Winner of the tile
			uint surfel_idx = atomicAdd(DEREF(surfel_spawn_count), 1);
			uint winner_pixel = winner_pixels[gl_SubgroupInvocationID];
			uvec2 winner_pixel_coords = uvec2(winner_pixel / pc.height, winner_pixel % pc.height);
			uint tiles_x = (pc.width + SURFELIZE_PASS_TILE_SIZE_XY - 1) / SURFELIZE_PASS_TILE_SIZE_XY;
			uint tiles_y = (pc.height + SURFELIZE_PASS_TILE_SIZE_XY - 1) / SURFELIZE_PASS_TILE_SIZE_XY;
			DEREF(surfel_spawn_list)[surfel_idx] = winner_pixel;
			uint max_surfels_to_spawn = tiles_x * tiles_y;
			ASSERT2(surfel_idx < max_surfels_to_spawn, "Surfel spawn idx exceeded (%u) the maximum number on %v2u\n",
					surfel_idx, winner_pixel_coords);
		}
	}
}
