#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

#include "../../bda.glsl"
#include "ir_commons.h"
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(binding = 1) uniform SceneUBOBuffer { SceneUBO ubo; };
#include "../../scene_buffers.glsl"

#include "ir_commons.glsl"

layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };

SCENE_BUFFER(g_buffer, SurfaceRef);
SCENE_BUFFER(surfel_spawn_list, uint);
SCENE_BUFFER_SCALAR(surfel_spawn_count, uint);
SCENE_BUFFER(surfel_free_stack, uint);
SCENE_BUFFER_SCALAR(surfel_free_stack_count, int);
SCENE_BUFFER(surfel_pool, Surfel);
SCENE_BUFFER(grid_cell_counts, uint);
SCENE_BUFFER(grid_cell_indices, uint);

#include "surfel_commons.glsl"
#include "grid.glsl"

void recycle_surfel(uint surfel_id) {
	DEREF(surfel_pool)[surfel_id].radius = 0;
	int idx = atomicAdd(DEREF(surfel_free_stack_count), 1);
	DEREF(surfel_free_stack)[idx] = surfel_id;
}

layout(local_size_x = ALLOCATE_PASS_WG_SIZE, local_size_y = 1, local_size_z = 1) in;
void main() {
	uint tid = gl_GlobalInvocationID.x;
	if(tid >= MAX_SURFEL_COUNT) {
		return;
	}

	Surfel s = DEREF(surfel_pool)[tid];

	if(s.radius <= 0.0f) {
		return;
	}

	if(s.age != pc.total_frame_num -1 ) {
		return;
	}

	SurfaceData hit_data = load_surface(s.gbuffer);

	vec4 cam_pos = ubo.inv_view * vec4(0, 0, 0, 1);

	uvec4 neighbors[MAX_NEIGHBOR_PLUS_ITSELF_COUNT];
	uint neighbor_count;

	collect_neighbors(hit_data.pos, s.radius, cam_pos.xyz, neighbors, neighbor_count);

	for (uint i = 0; i < neighbor_count; i++) {
		uint linear_idx = linearize_grid(neighbors[i]);
		uint surfel_offset = DEREF(grid_cell_counts)[linear_idx];
		uint surfel_count = DEREF(grid_cell_counts)[linear_idx + 1] - surfel_offset;
		for (uint gid = 0; gid < surfel_count; gid++) {
			uint sid = DEREF(grid_cell_indices)[gid + surfel_offset];
			Surfel other = DEREF(surfel_pool)[sid];
			if (other.radius <= 0.0) continue;
			SurfaceData other_hit_data = load_surface(other.gbuffer);

			vec3 pos_to_other = hit_data.pos - other_hit_data.pos;
			float dist_sqr = dot(pos_to_other, pos_to_other);
			float dist_normal = dot(pos_to_other, other_hit_data.n_s);
			float dist_tangent = sqrt(max(0.0, dist_sqr - dist_normal * dist_normal));
			float n_dot = dot(hit_data.n_s, other_hit_data.n_s);

			const float EPS = 1e-6;
			if (n_dot > 0.3 && dist_tangent <= (other.radius + s.radius + EPS)) {

				// earlier frame wins
				if((other.age < s.age) || other.age == s.age && sid < tid) {

					recycle_surfel(tid);
					return;
				}
			}
		}
	}
}
