#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

#include "../../bda.glsl"
#include "../../commons.glsl"
#include "ir_commons.h"
#include "ir_commons.glsl"
const uint flags = gl_RayFlagsOpaqueEXT;
const float tmin = 0.001;
const float tmax = 10000.0;
layout(location = 0) rayPayloadEXT SurfaceHitPayload payload;
layout(location = 1) rayPayloadEXT AnyHitPayload any_hit_payload;
layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };

#include "direct_lighting.glsl"

SCENE_BUFFER(surfel_pool, Surfel);

SCENE_BUFFER(surfel_samples, SurfelSample);

uvec4 sampling_seed = init_rng(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy, pc.sampling_seed);

void main() {
	uint tid = gl_LaunchIDEXT.y;
	if (tid >= MAX_SURFEL_COUNT) {
		return;
	}

	Surfel surfel = DEREF(surfel_pool)[tid];

	if (surfel.radius <= 0.0f) {
		return;
	}

	SurfaceData surfel_hit_data = load_surface(surfel.gbuffer);
	vec3 surfel_origin = surfel_hit_data.pos;
	vec3 camera_origin = ubo.inv_view[3].xyz;
	vec3 wo = normalize(camera_origin - surfel_origin);
	Material material = load_material(surfel_hit_data.material_idx, surfel_hit_data.uv);

	vec3 n_s = surfel_hit_data.n_s;
	vec3 n_g = surfel_hit_data.n_g;
	bool side = face_forward(n_s, n_g, wo);
	vec3 wi;
	float pdf_w;
	float cos_theta;

	// We're already on a surface, sample the BSDF
	sample_bsdf(n_s, n_g, wo, material, TRANSPORT_MODE_FROM_CAMERA, side, wi, pdf_w, cos_theta, sampling_seed);
	
	if (pdf_w <= 0.0 || cos_theta <= 0.0) {
		return;
	}

	surfel_origin = offset_ray(surfel_origin, n_g, wi);

	traceRayEXT(tlas, flags, 0x1, 0, 0, 0, surfel_origin, tmin, wi, tmax, 0);
	const bool found_isect = surface_ref_valid(payload.surface);

	vec3 radiance = vec3(0);
	if (!found_isect) {
#ifdef ENABLE_ATMOSPHERE
		vec3 atmosphere_L = shade_atmosphere(pc.dir_light_idx, pc.sky_col, surfel_origin, wi, tmax);
#else
		vec3 atmosphere_L = pc.sky_col;
#endif	// ENABLE_ATMOSPHERE
		radiance += atmosphere_L;
	} else {
		SurfaceData hit_data = load_surface(payload.surface);

		vec3 wo = -wi;
		Material hit_material = load_material(hit_data.material_idx, hit_data.uv);

		bool forward_facing = face_forward(hit_data.n_s, hit_data.n_g, wo);
		radiance += sample_direct_light(sampling_seed, hit_data.pos, hit_data.n_s, hit_data.n_g, wo, hit_material,
										forward_facing);
	}

	SurfelSample surfel_sample;
	surfel_sample.radiance = radiance * cos_theta / pdf_w;
	surfel_sample.hit_t = payload.dist;

	uint linear_idx = gl_LaunchIDEXT.y * pc.rays_per_surfel + gl_LaunchIDEXT.x;
	DEREF(surfel_samples)[linear_idx] = surfel_sample;
}
