#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

#include "../../bda.glsl"
#include "ir_commons.h"
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };

layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };

SCENE_BUFFER(surfel_pool, Surfel);
SCENE_BUFFER(surfel_samples, SurfelSample);

layout(local_size_x = DEFAULT_WG_SIZE, local_size_y = 1, local_size_z = 1) in;
// One invocation per surfel
void main() {
	// TODO: Use shared memory
	uint surfel_id = gl_GlobalInvocationID.x;

	if(surfel_id >= MAX_SURFEL_COUNT || pc.rays_per_surfel == 0u) {
		return;
	}
	Surfel surfel = DEREF(surfel_pool)[surfel_id];
	if(surfel.radius <= 0.0f) {
		return;
	}

	vec3 irradiance = vec3(0);
	for(uint i = 0; i < pc.rays_per_surfel; i++) {
		uint linear_idx = surfel_id * pc.rays_per_surfel + i;
		irradiance += DEREF(surfel_samples)[linear_idx].radiance;
	}
	irradiance /= float(pc.rays_per_surfel);
	const float alpha = 0.01f;
	surfel.irradiance = surfel.irradiance + (irradiance - surfel.irradiance) * alpha;

	DEREF(surfel_pool)[surfel_id] = surfel;
}
