#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

#include "ir_commons.h"
layout(binding = 0) buffer SceneDesc_ { SceneDesc scene_desc; };
layout(binding = 1) uniform SceneUBOBuffer { SceneUBO ubo; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer InstanceInfo { PrimInfo d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer Indices { uint i[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer CompactVertices { Vertex d[]; };

Indices indices = Indices(scene_desc.index_addr);
InstanceInfo prim_infos = InstanceInfo(scene_desc.prim_info_addr);
CompactVertices compact_vertices = CompactVertices(scene_desc.compact_vertices_addr);

#include "ir_commons.glsl"

layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer InGBuffer { GBuffer d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer SurfelSpawnList { uint d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer SurfelSpawnCount { uint d; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer SurfelPool { Surfel d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer SurfelFreeStack { uint d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer SurfelFreeStackCount { int d; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer GridCellCounts { uint d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer GridCellIndices { uint d[]; };

InGBuffer gbuffers = InGBuffer(scene_desc.g_buffer_addr);
SurfelSpawnList spawn_list = SurfelSpawnList(scene_desc.surfel_spawn_list_addr);
SurfelSpawnCount spawn_count = SurfelSpawnCount(scene_desc.surfel_spawn_count_addr);
SurfelFreeStack free_stack = SurfelFreeStack(scene_desc.surfel_free_stack_addr);
SurfelFreeStackCount free_stack_count = SurfelFreeStackCount(scene_desc.surfel_free_stack_count_addr);
SurfelPool surfel_pool = SurfelPool(scene_desc.surfel_pool_addr);
GridCellCounts grid_cell_counts = GridCellCounts(scene_desc.grid_cell_counts_addr);
GridCellIndices grid_cell_indices = GridCellIndices(scene_desc.grid_cell_indices_addr);

#include "surfel_commons.glsl"
#include "grid.glsl"

void recycle_surfel(uint surfel_id) {
	surfel_pool.d[surfel_id].radius = 0;
	int idx = atomicAdd(free_stack_count.d, 1);
	free_stack.d[idx] = surfel_id;
}

layout(local_size_x = ALLOCATE_PASS_WG_SIZE, local_size_y = 1, local_size_z = 1) in;
void main() {
	uint tid = gl_GlobalInvocationID.x;
	if(tid >= MAX_SURFEL_COUNT) {
		return;
	}

	Surfel s = surfel_pool.d[tid];

	if(s.radius <= 0.0f) {
		return;
	}

	if(s.age != pc.total_frame_num -1 ) {
		return;
	}

	HitData hit_data = get_hitdata(s.gbuffer);

	vec4 cam_pos = ubo.inv_view * vec4(0, 0, 0, 1);

	uvec4 neighbors[MAX_NEIGHBOR_PLUS_ITSELF_COUNT];
	uint neighbor_count;

	collect_neighbors(hit_data.pos, s.radius, cam_pos.xyz, neighbors, neighbor_count);

	for (uint i = 0; i < neighbor_count; i++) {
		uint linear_idx = linearize_grid(neighbors[i]);
		uint surfel_offset = grid_cell_counts.d[linear_idx];
		uint surfel_count = grid_cell_counts.d[linear_idx + 1] - surfel_offset;
		for (uint gid = 0; gid < surfel_count; gid++) {
			uint sid = grid_cell_indices.d[gid + surfel_offset];
			Surfel other = surfel_pool.d[sid];
			if (other.radius <= 0.0) continue;
			HitData other_hit_data = get_hitdata(other.gbuffer);

			vec3 pos_to_other = hit_data.pos - other_hit_data.pos;
			float dist_sqr = dot(pos_to_other, pos_to_other);
			float dist_normal = dot(pos_to_other, other_hit_data.n_s);
			float dist_tangent = sqrt(max(0.0, dist_sqr - dist_normal * dist_normal));
			float n_dot = dot(hit_data.n_s, other_hit_data.n_s);

			const float EPS = 1e-6;
			if (n_dot > 0.3 && dist_tangent <= (other.radius + s.radius + EPS)) {

				// earlier frame wins
				if((other.age < s.age) || other.age == s.age && sid < tid) {

					recycle_surfel(tid);
					return;
				}
			}
		}
	}
}
