#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

#define UINT32_MAX 4294967295u
#include "ir_commons.glsl"
const uint flags = gl_RayFlagsOpaqueEXT;
const float tmin = 0.001;
const float tmax = 10000.0;
uint pixel_idx = (gl_LaunchIDEXT.x * gl_LaunchSizeEXT.y + gl_LaunchIDEXT.y);
layout(location = 0) rayPayloadEXT IRCacheHitPayload payload;
layout(location = 1) rayPayloadEXT AnyHitPayload any_hit_payload;
layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer OutGBuffer { GBuffer d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer HashEntryBuffer { HashEntry d[]; };

OutGBuffer gbuffers = OutGBuffer(scene_desc.g_buffer_addr);
HashEntryBuffer hash_entries = HashEntryBuffer(scene_desc.hash_cells_addr);

void main() {
	GBuffer gbuffer = gbuffers.d[pixel_idx];
	if (!gbuffer_valid(gbuffer)) {
		return;
	}

	HitData hit_data =
		get_hitdata(gbuffer.barycentrics, gbuffer.primitive_instance_id.y, gbuffer.primitive_instance_id.x);

	HashKey key;
	key.pos =
		quantize_pos(hit_data.pos, ubo.view_pos.xyz, ubo.fovy, pc.height, pc.desired_px_per_cell, pc.min_cell_size, pc.min_bounds);
	key.normal = quantize_normal(hit_data.n_s);
	key.material = hit_data.material_idx;
	uint quantized_key = hash_key(key);
	uint hash_idx = quantized_key % pc.max_hash_table_size;
	HashEntry entry = hash_entries.d[hash_idx];
	if (ubo.debug_click == 1 && ivec2(gl_LaunchIDEXT.xy) == ubo.clicked_pos) {
		LOG_CLICKED2("Clicked: %v2i - Selected: %v2i\n", ivec2(gl_LaunchIDEXT.xy), entry.pixel);
		vec3 col = vec3(1, 0, 0);
		imageStore(image, entry.pixel, vec4(col, 1.f));
	}
}