#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require

#define UINT32_MAX 4294967295u
#include "ir_commons.glsl"
const uint flags = gl_RayFlagsOpaqueEXT;
const float tmin = 0.001;
const float tmax = 10000.0;
layout(location = 0) rayPayloadEXT IRCacheHitPayload payload;
layout(location = 1) rayPayloadEXT AnyHitPayload any_hit_payload;
layout(push_constant) uniform _PushConstantRay { PCIRCache pc; };
layout(buffer_reference, scalar, buffer_reference_align = 4) readonly buffer InGBuffer { GBuffer d[]; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer HashEntryBuffer { HashEntry d[]; };

InGBuffer gbuffers = InGBuffer(scene_desc.g_buffer_addr);
HashEntryBuffer hash_entries = HashEntryBuffer(scene_desc.hash_cells_addr);

float compute_cell_size(vec3 pos, vec3 cam_pos, float fovy, float viewport_height, float desired_px_size) {
	vec3 to_pos = pos - cam_pos;
	return (2 * desired_px_size * max(abs(to_pos.x), max(abs(to_pos.y), abs(to_pos.z))) * tan(radians(fovy / 2))) /
		   viewport_height;
}

uvec3 quantize_pos(vec3 pos, vec3 cam_pos, float fovy, float viewport_height, float desired_px_size,
				   float base_cell_size) {
	vec3 aligned_pos = pos - pc.min_bounds;
	vec3 cell_center = pc.min_bounds + (vec3(uvec3(floor(aligned_pos / base_cell_size))) + 0.5) * base_cell_size;
	float s_k = compute_cell_size(cell_center, cam_pos, fovy, viewport_height, desired_px_size);
	float s_cell = base_cell_size * ceil(s_k / base_cell_size);
	return uvec3(floor((aligned_pos / s_cell)));
}

uint quantize_normal(vec3 normal) {
	const uint MAX_QUANT = 1 << 4;
	float theta = atan(length(normal.xy), normal.z);
	float phi = atan(normal.y, normal.x);
	if (phi < 0.0) phi += 2.0 * PI;
	uint theta_packed = uint((theta / PI) * float(MAX_QUANT));
	uint phi_packed = uint((phi / (2.0 * PI)) * float(MAX_QUANT));
	return theta_packed * MAX_QUANT + phi_packed;
}

uint hash_key(HashKey key) { return xxhash32(uvec2(xxhash32(uvec4(key.pos, key.normal)), key.material)); }

uvec4 seed = init_rng(gl_LaunchIDEXT.xy, gl_LaunchSizeEXT.xy, pc.frame_num);

vec3 do_nee(inout uvec4 seed, vec3 pos, Material hit_mat, bool side, vec3 n_s, vec3 wo) {
	float pdf_light_a;
	vec3 wi = vec3(0);
	float wi_len = 0;
	float cos_from_light;
	float pdf_light_w;
	LightRecord record;
	vec3 Le = sample_Li(rand4(seed), pos, pc.num_lights, pdf_light_w, wi, wi_len, pdf_light_a, cos_from_light, record);
	const vec3 p = offset_ray2(pos, n_s);
	float light_bsdf_pdf;
	float cos_x = dot(n_s, wi);
	vec3 f_light = eval_bsdf(n_s, wo, hit_mat, 1, side, wi, light_bsdf_pdf);
	any_hit_payload.hit = 1;
	traceRayEXT(tlas, gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsSkipClosestHitShaderEXT, 0xFF, 1, 0, 1, p, 0, wi,
				wi_len - EPS, 1);
	bool visible = any_hit_payload.hit == 0;
	bool is_directional_light = get_light_type(record.flags) == LIGHT_DIRECTIONAL;

	const float light_pick_pdf = 1. / pc.light_triangle_count;
	if (visible && pdf_light_w > 0) {
		float mis_weight = is_light_delta(record.flags) ? 1 : 1 / (1 + light_bsdf_pdf / pdf_light_w);
		return mis_weight * f_light * abs(cos_x) * Le / (light_pick_pdf * pdf_light_w);
	}
	return vec3(0);
}

void main() {
	HashEntry entry = hash_entries.d[gl_LaunchIDEXT.x];
	GBuffer gbuffer = entry.representative_point;
	if (!gbuffer_valid(gbuffer)) {
		return;
	}
	HitData gbuffer_data =
		get_hitdata(gbuffer.barycentrics, gbuffer.primitive_instance_id.y, gbuffer.primitive_instance_id.x);

	const Material origin_mat = load_material(gbuffer_data.material_idx, gbuffer_data.uv);
	vec3 wo = normalize(ubo.view_pos.xyz - gbuffer_data.pos);
	vec3 n_s = gbuffer_data.n_s;
	vec3 n_g = gbuffer_data.n_g;

	bool side = face_forward(n_s, n_g, wo);
	float cos_theta;
	vec3 direction;
	float bsdf_pdf_val;
	const vec3 f = sample_bsdf(n_s, wo, origin_mat, 1 /*radiance=cam*/, side, direction, bsdf_pdf_val, cos_theta, seed);

	vec3 origin = offset_ray(gbuffer_data.pos, n_g);
	traceRayEXT(tlas, flags, 0x1, 0, 0, 0, origin, tmin, direction, tmax, 0);
	const bool found_isect = payload.instance_idx != -1;
	if(!found_isect) {
		return;
	}

	HitData hit_data = get_hitdata(payload.attribs, payload.instance_idx, payload.triangle_idx);
	const Material hit_mat = load_material(hit_data.material_idx, hit_data.uv);
	vec3 L = do_nee(seed, hit_data.pos, hit_mat, side, hit_data.n_s, wo);
	vec3 throughput = f * abs(cos_theta) / bsdf_pdf_val;
}