#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_atomic_float : require
// Includes all the buffer addresses and indices
#include "smlt_commons.h"
#include "smlt_commons.glsl"
void main() {
#define mlt_sampler DEREF(mlt_samplers)[mlt_sampler_idx]
#define past_splat(i) DEREF(past_splat)[splat_idx + i]
#define splat(i) DEREF(splat)[splat_idx + i]
    uvec4 chain_seed = DEREF(seeds)[pixel_idx].chain_seed;
    mlt_start_chain(0);

    large_step = true;
    save_radiance = true;
    mlt_seed = chain_seed;

    mlt_L_light();
    DEREF(seeds)[pixel_idx].chain_seed = mlt_seed;
}
